
serverlist = []

serverlist.append(['ayahoo.com',0,'ayahoo.com'])
serverlist.append(['yahoomail.com',0,'yahoomail.com'])
serverlist.append(['yaoo.com',0,'ayahoo.com'])

# serverList = ['gmail.com','yahoo.com','google.com','rediffmail.com','email.com','desai.com','hotmail.com','yahoo.co.in','yahoo.in','gnsik.com','ymail.com','outlook.com','innovativeinfotech.com','gamil.com','csc.com','gmai.com','facebook.com','yah00.co.in','df.dsd','rediff.com','yshoo.in','citi.com','mail.com','qq.com','denabank.co.in','dsd.com','ssoia.com','wgs.com','we.com','g.fv','askiitians.com','yaoo.com','m.com','itbhu.ac.in','GMMAIL.COM','sed.in','iitbbs.ac.in','ter.com','erdiffmail.com','iitp.ac.in','indianoil.in','gg.com','ovi.com','gamail.com','rocketmail.com','JA.CMP','gawab.com','net.com','iiitd.ac.in','nokiamail.com','hotmail.co.uk','84gmail.com','sdm.com','gmail.nbv','sdg.com','g.com','gmail.co.in','gma.com','sdfgsd.com','sag.com','gma.co','efg.sdgv','ssdfg.fgjh','msn.com','yohoo.co.in','rediffmaol.com','live.com','jecrc.ac.in','hjf.con','fbth.in','tbg.bt','7670Gmail.com','delhipress.in','raju.com','reddifmail.com','kollmail.in','gmamill.com','5.com','asdfgh.com','sailrsp.co.in','powericaltd.com','gmail.comm','imt.edu','pc.com','omifco.com','aramuc.net','ayahoo.com','in.com','yhoo.in','dadhaniya07.gmail.com','eil.co.in','gmail.in','yahoo.co.uk','prismcement.com','jdjf.com','kjh.com','sfg.xjn','rbsgroup.in','12.com','sbi.co.in','dkdk.com','jmda.com','f.com','14m15gmail.co','gmaail.com','padmakshi.com','iitk.ac.in','ujm.com','drbrajnish.com','jhgh.vioj','gmain.com','hjj.com','hgke.com','koolmail.in','yyhgs.fhj','fggh.com','gnvaeh.com','hsb.com','hjfhjf.com','faceboo.com','gf.com','ygff.ff','jh.com','hh.com','gghghg.com','superrito.com','rsefas.com','DSKFJDKF.COM','hgdf.com','yf.com','sj.com','yaoo.co','gh.gdf','fgfed.grf','gai.com','hddd.com','hpcl.co.in','fhdfh.com','sdaf.com','dsfs.com','rknec.edu','yahoomail.com','re.com','fsdf.in','g-mail.com','gmsil.com','tmail.com','hrkede.com','hhh.com','hpl.co.in','murga.com','yaho.co.in','ljl.com','milacron.com','7588.com','yamial.com','sfdgdf.com','sff.com','d.in','sajh.in','bg-group.com','bsnl.co.in','nmct.co.in','hmail.com','hsj.com','wgw.com','afdsd.com','2013gmail.com','adityawrites.com','iiitr.ernet.in','zsdgdsf.com','abc.com','pqy.com','fgh.com','cmail.com','jsd.com','sss.com','drdrb.net','ds.com','bc.com','b.comq','gha.com','erewr.com','acme.in','ss.ss','icicisecurities.com','live.in','licindia.com','nic.co.in','61gmail.com','nvsoft.com','heterodrugs.com','mail.in','tges.org']
#

serverlist.append(['gmail.com',10,'alt1.gmail-smtp-in.l.google.com'])
serverlist.append(['gmail.com',5,'gmail-smtp-in.l.google.com'])
serverlist.append(['gmail.com',30,'alt3.gmail-smtp-in.l.google.com'])
serverlist.append(['gmail.com',40,'alt4.gmail-smtp-in.l.google.com'])
serverlist.append(['gmail.com',20,'alt2.gmail-smtp-in.l.google.com'])
serverlist.append(['yahoo.com',1,'mta7.am0.yahoodns.net'])
serverlist.append(['yahoo.com',1,'mta6.am0.yahoodns.net'])
serverlist.append(['yahoo.com',1,'mta5.am0.yahoodns.net'])
serverlist.append(['google.com',50,'alt4.aspmx.l.google.com'])
serverlist.append(['google.com',30,'alt2.aspmx.l.google.com'])
serverlist.append(['google.com',40,'alt3.aspmx.l.google.com'])
serverlist.append(['google.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['google.com',10,'aspmx.l.google.com'])
serverlist.append(['rediffmail.com',5,'mx.rediffmail.rediff.akadns.net'])
serverlist.append(['email.com',10,'mx00.gmx.com'])
serverlist.append(['email.com',10,'mx01.gmx.com'])
serverlist.append(['desai.com',50,'smtp.desai.com'])
serverlist.append(['desai.com',10,'desai.com.inbound15.mxlogicmx.net'])
serverlist.append(['desai.com',5,'desai.com.inbound15.mxlogic.net'])
serverlist.append(['hotmail.com',5,'mx3.hotmail.com'])
serverlist.append(['hotmail.com',5,'mx4.hotmail.com'])
serverlist.append(['hotmail.com',5,'mx1.hotmail.com'])
serverlist.append(['hotmail.com',5,'mx2.hotmail.com'])
serverlist.append(['yahoo.co.in',10,'mx-apac.mail.gm0.yahoodns.net'])
serverlist.append(['yahoo.in',10,'mx-apac.mail.gm0.yahoodns.net'])
serverlist.append(['ymail.com',10,'mta6.am0.yahoodns.net'])
serverlist.append(['ymail.com',10,'mta5.am0.yahoodns.net'])
serverlist.append(['ymail.com',10,'mta7.am0.yahoodns.net'])
serverlist.append(['outlook.com',10,'mx4.hotmail.com'])
serverlist.append(['outlook.com',10,'mx1.hotmail.com'])
serverlist.append(['outlook.com',10,'mx2.hotmail.com'])
serverlist.append(['outlook.com',10,'mx3.hotmail.com'])
serverlist.append(['innovativeinfotech.com',10,'aspmx.l.google.com'])
serverlist.append(['innovativeinfotech.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['innovativeinfotech.com',30,'alt2.aspmx.l.google.com'])
serverlist.append(['innovativeinfotech.com',40,'aspmx2.googlemail.com'])
serverlist.append(['innovativeinfotech.com',50,'aspmx3.googlemail.com'])
serverlist.append(['gamil.com',10,'mx8.webfaction.com'])
serverlist.append(['gamil.com',10,'mx7.webfaction.com'])
serverlist.append(['gamil.com',10,'mx9.webfaction.com'])
serverlist.append(['csc.com',10,'cluster4.us.messagelabs.com'])
serverlist.append(['csc.com',20,'cluster4a.us.messagelabs.com'])
serverlist.append(['gmai.com',5,'mail.b-io.co'])
serverlist.append(['facebook.com',10,'msgin.vvv.facebook.com'])
serverlist.append(['yah00.co.in',0,'yah00.co.in'])
serverlist.append(['rediff.com',10,'mx.rediffmail.rediff.akadns.net'])
serverlist.append(['citi.com',5,'mx-a.mail.citi.com'])
serverlist.append(['citi.com',5,'mx-b.mail.citi.com'])
serverlist.append(['mail.com',10,'mx01.gmx.com'])
serverlist.append(['mail.com',10,'mx00.gmx.com'])
serverlist.append(['qq.com',20,'mx2.qq.com'])
serverlist.append(['qq.com',30,'mx1.qq.com'])
serverlist.append(['qq.com',10,'mx3.qq.com'])
serverlist.append(['denabank.co.in',10,'smtp1.denabank.co.in'])
serverlist.append(['denabank.co.in',20,'smtp2.denabank.co.in'])
serverlist.append(['denabank.co.in',30,'smtp3.denabank.co.in'])
serverlist.append(['dsd.com',30,'mx.dsd.com'])
serverlist.append(['ssoia.com',10,'do6.fishyes.info'])
serverlist.append(['wgs.com',0,'mail.b-io.co'])
serverlist.append(['we.com',10,'we-com.mail.protection.outlook.com'])
serverlist.append(['askiitians.com',30,'aspmx2.googlemail.com'])
serverlist.append(['askiitians.com',30,'aspmx5.googlemail.com'])
serverlist.append(['askiitians.com',30,'aspmx3.googlemail.com'])
serverlist.append(['askiitians.com',10,'aspmx.l.google.com'])
serverlist.append(['askiitians.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['askiitians.com',20,'alt2.aspmx.l.google.com'])
serverlist.append(['askiitians.com',30,'aspmx4.googlemail.com'])
serverlist.append(['itbhu.ac.in',5,'alt1.aspmx.l.google.com'])
serverlist.append(['itbhu.ac.in',1,'aspmx.l.google.com'])
serverlist.append(['itbhu.ac.in',5,'alt2.aspmx.l.google.com'])
serverlist.append(['itbhu.ac.in',10,'aspmx2.googlemail.com'])
serverlist.append(['itbhu.ac.in',10,'aspmx3.googlemail.com'])
serverlist.append(['GMMAIL.COM',100,'mx1.GMMAIL.COM'])
serverlist.append(['iitbbs.ac.in',10,'aspmx2.googlemail.com'])
serverlist.append(['iitbbs.ac.in',10,'aspmx3.googlemail.com'])
serverlist.append(['iitbbs.ac.in',1,'aspmx.l.google.com'])
serverlist.append(['iitbbs.ac.in',5,'alt1.aspmx.l.google.com'])
serverlist.append(['iitbbs.ac.in',5,'alt2.aspmx.l.google.com'])
serverlist.append(['ter.com',10,'ter-com.mail.protection.outlook.com'])
serverlist.append(['iitp.ac.in',10,'magadh.iitp.ac.in'])
serverlist.append(['iitp.ac.in',20,'magadh-rail.iitp.ac.in'])
serverlist.append(['indianoil.in',10,'xtracare2.indianoil.in'])
serverlist.append(['indianoil.in',10,'sanchar.indianoil.co.in'])
serverlist.append(['indianoil.in',10,'xtracare1.indianoil.in'])
serverlist.append(['gg.com',30,'aspmx5.google.com'])
serverlist.append(['gg.com',30,'aspmx3.google.com'])
serverlist.append(['gg.com',10,'aspmx.l.google.com'])
serverlist.append(['gg.com',30,'aspmx2.google.com'])
serverlist.append(['gg.com',30,'aspmx4.google.com'])
serverlist.append(['gg.com',20,'alt2.aspmx.l.google.com'])
serverlist.append(['gg.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['ovi.com',1,'mta5.am0.yahoodns.net'])
serverlist.append(['ovi.com',1,'mta7.am0.yahoodns.net'])
serverlist.append(['ovi.com',1,'mta6.am0.yahoodns.net'])
serverlist.append(['gamail.com',0,'mail.b-io.co'])
serverlist.append(['rocketmail.com',10,'mta5.am0.yahoodns.net'])
serverlist.append(['rocketmail.com',10,'mta7.am0.yahoodns.net'])
serverlist.append(['rocketmail.com',10,'mta6.am0.yahoodns.net'])
serverlist.append(['net.com',10,'sonusnet.com.inbound10.mxlogicmx.net'])
serverlist.append(['net.com',10,'sonusnet.com.inbound10.mxlogic.net'])
serverlist.append(['iiitd.ac.in',5,'alt2.aspmx.l.google.com'])
serverlist.append(['iiitd.ac.in',10,'alt3.aspmx.l.google.com'])
serverlist.append(['iiitd.ac.in',10,'alt4.aspmx.l.google.com'])
serverlist.append(['iiitd.ac.in',0,'aspmx.l.google.com'])
serverlist.append(['iiitd.ac.in',5,'alt1.aspmx.l.google.com'])
serverlist.append(['nokiamail.com',1,'mta5.am0.yahoodns.net'])
serverlist.append(['nokiamail.com',1,'mta6.am0.yahoodns.net'])
serverlist.append(['nokiamail.com',1,'mta7.am0.yahoodns.net'])
serverlist.append(['hotmail.co.uk',5,'mx3.hotmail.com'])
serverlist.append(['hotmail.co.uk',5,'mx4.hotmail.com'])
serverlist.append(['hotmail.co.uk',5,'mx2.hotmail.com'])
serverlist.append(['sdg.com',90,'mail5.sdg.com'])
serverlist.append(['sdg.com',100,'mail4.sdg.com'])
serverlist.append(['sdg.com',80,'mail3.sdg.com'])
serverlist.append(['sdg.com',20,'sdg.com.s5b2.psmtp.com'])
serverlist.append(['sdg.com',15,'sdg.com.s5b1.psmtp.com'])
serverlist.append(['sdg.com',10,'sdg.com.s5a2.psmtp.com'])
serverlist.append(['sdg.com',5,'sdg.com.s5a1.psmtp.com'])
serverlist.append(['sag.com',11,'mailgateway02.sag.com'])
serverlist.append(['sag.com',10,'mail.sag.com'])
serverlist.append(['gma.co',10,'mailstore1.europe.secureserver.net'])
serverlist.append(['gma.co',0,'smtp.europe.secureserver.net'])
serverlist.append(['msn.com',5,'mx1.hotmail.com'])
serverlist.append(['msn.com',5,'mx2.hotmail.com'])
serverlist.append(['msn.com',5,'mx3.hotmail.com'])
serverlist.append(['msn.com',5,'mx4.hotmail.com'])
serverlist.append(['live.com',5,'mx3.hotmail.com'])
serverlist.append(['live.com',5,'mx4.hotmail.com'])
serverlist.append(['live.com',5,'mx1.hotmail.com'])
serverlist.append(['live.com',5,'mx2.hotmail.com'])
serverlist.append(['jecrc.ac.in',20,'aspmx2.googlemail.com'])
serverlist.append(['jecrc.ac.in',5,'aspmx.l.google.com'])
serverlist.append(['jecrc.ac.in',10,'alt1.aspmx.l.google.com'])
serverlist.append(['delhipress.in',0,'mail.rediffmailpro.com'])
serverlist.append(['sailrsp.co.in',10,'sailrsp.co.in'])
serverlist.append(['powericaltd.com',5,'alt1.aspmx.l.google.com'])
serverlist.append(['powericaltd.com',10,'aspmx3.googlemail.com'])
serverlist.append(['powericaltd.com',5,'alt2.aspmx.l.google.com'])
serverlist.append(['powericaltd.com',10,'aspmx2.googlemail.com'])
serverlist.append(['powericaltd.com',1,'aspmx.l.google.com'])
serverlist.append(['imt.edu',20,'mail1.imt.edu'])
serverlist.append(['imt.edu',10,'mail.imt.edu'])
serverlist.append(['omifco.com',0,'webmail.omifco.com'])
serverlist.append(['omifco.com',5,'mail.omifco.com'])
serverlist.append(['aramuc.net',30,'alt2.aspmx.l.google.com'])
serverlist.append(['aramuc.net',40,'aspmx2.googlemail.com'])
serverlist.append(['aramuc.net',50,'aspmx3.googlemail.com'])
serverlist.append(['aramuc.net',60,'aspmx4.googlemail.com'])
serverlist.append(['aramuc.net',70,'aspmx5.googlemail.com'])
serverlist.append(['aramuc.net',10,'aspmx.l.google.com'])
serverlist.append(['in.com',5,'mxa.expurgate.net'])
serverlist.append(['in.com',5,'mxb.expurgate.de'])
serverlist.append(['in.com',5,'mxb.expurgate.net'])
serverlist.append(['in.com',5,'mxa.expurgate.de'])
serverlist.append(['yhoo.in',0,'mail.b-io.co'])
serverlist.append(['eil.co.in',10,'mx121.eil.co.in'])
serverlist.append(['yahoo.co.uk',10,'mx-eu.mail.am0.yahoodns.net'])
serverlist.append(['prismcement.com',10,'cluster6.us.messagelabs.com'])
serverlist.append(['prismcement.com',20,'cluster6a.us.messagelabs.com'])
serverlist.append(['rbsgroup.in',10,'mail.rediffmailpro.com'])
serverlist.append(['12.com',0,'mail.b-io.co'])
serverlist.append(['sbi.co.in',10,'mx1.sbi.co.in'])
serverlist.append(['sbi.co.in',30,'mx2.sbi.co.in'])
serverlist.append(['sbi.co.in',10,'mx3.sbi.co.in'])
serverlist.append(['sbi.co.in',30,'mx4.sbi.co.in'])
serverlist.append(['dkdk.com',0,'mail.b-io.co'])
serverlist.append(['padmakshi.com',20,'alt2.aspmx.l.google.com'])
serverlist.append(['padmakshi.com',30,'aspmx3.googlemail.com'])
serverlist.append(['padmakshi.com',10,'aspmx.l.google.com'])
serverlist.append(['padmakshi.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['padmakshi.com',30,'aspmx4.googlemail.com'])
serverlist.append(['padmakshi.com',30,'aspmx2.googlemail.com'])
serverlist.append(['iitk.ac.in',10,'mail0.iitk.ac.in'])
serverlist.append(['iitk.ac.in',10,'mail1.iitk.ac.in'])
serverlist.append(['ujm.com',10,'mail2a.smtproutes.org'])
serverlist.append(['ujm.com',10,'mail2b.smtproutes.org'])
serverlist.append(['drbrajnish.com',10,'mail.drbrajnish.com'])
serverlist.append(['gmain.com',5,'mail.b-io.co'])
serverlist.append(['hgke.com',5,'mail.b-io.co'])
serverlist.append(['koolmail.in',10,'560464235.pamx1.hotmail.com'])
serverlist.append(['gf.com',10,'fw.gf.com'])
serverlist.append(['hh.com',10,'mailserv.hh.com'])
serverlist.append(['superrito.com',10,'fmg-mail-1.fakemailgenerator.com'])
serverlist.append(['superrito.com',10,'fmg-mail-2.fakemailgenerator.com'])
serverlist.append(['hgdf.com',5,'mail.b-io.co'])
serverlist.append(['yf.com',10,'smtp.yf.com'])
serverlist.append(['sj.com',10,'dev.null'])
serverlist.append(['gai.com',5,'gaig.mail.protection.outlook.com'])
serverlist.append(['hddd.com',0,'mail.b-io.co'])
serverlist.append(['hpcl.co.in',20,'egateisc02.hpcl.co.in'])
serverlist.append(['hpcl.co.in',30,'egateph01.hpcl.co.in'])
serverlist.append(['hpcl.co.in',10,'egateisc01.hpcl.co.in'])
serverlist.append(['fhdfh.com',0,'anmail.namebrightmail.com'])
serverlist.append(['dsfs.com',30,'alt3.aspmx.l.google.com'])
serverlist.append(['dsfs.com',30,'alt4.aspmx.l.google.com'])
serverlist.append(['dsfs.com',10,'aspmx.l.google.com'])
serverlist.append(['dsfs.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['dsfs.com',20,'alt2.aspmx.l.google.com'])
serverlist.append(['rknec.edu',10,'aspmx2.googlemail.com'])
serverlist.append(['rknec.edu',20,'mail.rknec.edu'])
serverlist.append(['rknec.edu',5,'alt1.aspmx.l.google.com'])
serverlist.append(['rknec.edu',1,'aspmx.l.google.com'])
serverlist.append(['rknec.edu',5,'alt2.aspmx.l.google.com'])
serverlist.append(['rknec.edu',30,'mail2.rknec.edu'])
serverlist.append(['rknec.edu',10,'aspmx3.googlemail.com'])
serverlist.append(['gmsil.com',10,'gmsil.com.1.0001.arsmtp.com'])
serverlist.append(['gmsil.com',20,'gmsil.com.2.0001.arsmtp.com'])
serverlist.append(['hhh.com',0,'mail.hhh.com'])
serverlist.append(['hpl.co.in',10,'smtpcal.hpl.co.in'])
serverlist.append(['murga.com',10,'nullmx.murga.com'])
serverlist.append(['ljl.com',0,'smtp.secureserver.net'])
serverlist.append(['ljl.com',10,'mailstore1.secureserver.net'])
serverlist.append(['7588.com',10,'mailstore1.secureserver.net'])
serverlist.append(['7588.com',0,'smtp.secureserver.net'])
serverlist.append(['yamial.com',12032,'mail.b-io.co'])
serverlist.append(['bg-group.com',100,'mail03.bg-group.com'])
serverlist.append(['bg-group.com',10,'mail01.bg-group.com'])
serverlist.append(['bg-group.com',10,'mail02.bg-group.com'])
serverlist.append(['bsnl.co.in',10,'bsnl.dildns.com'])
serverlist.append(['bsnl.co.in',10,'bsnlmx.xgen.in'])
serverlist.append(['nmct.co.in',40,'aspmx2.googlemail.com'])
serverlist.append(['nmct.co.in',50,'aspmx3.googlemail.com'])
serverlist.append(['nmct.co.in',10,'aspmx.l.google.com'])
serverlist.append(['nmct.co.in',20,'alt1.aspmx.l.google.com'])
serverlist.append(['nmct.co.in',30,'alt2.aspmx.l.google.com'])
serverlist.append(['hmail.com',0,'hmail.com'])
serverlist.append(['hsj.com',10,'mail1311.ixwebhosting.com'])
serverlist.append(['wgw.com',10,'aspmx.l.google.com'])
serverlist.append(['wgw.com',20,'alt1.aspmx.l.google.com'])
serverlist.append(['wgw.com',30,'alt2.aspmx.l.google.com'])
serverlist.append(['wgw.com',40,'aspmx2.googlemail.com'])
serverlist.append(['wgw.com',50,'aspmx3.googlemail.com'])
serverlist.append(['afdsd.com',25,'mx.afdsd.com'])
serverlist.append(['abc.com',5,'cluster6.us.messagelabs.com'])
serverlist.append(['abc.com',20,'cluster6a.us.messagelabs.com'])
serverlist.append(['jsd.com',1,'jsd.com'])
serverlist.append(['sss.com',1,'mail1.no-ip.com'])
serverlist.append(['sss.com',2,'mail2.no-ip.com'])
serverlist.append(['ds.com',0,'smtp.secureserver.net'])
serverlist.append(['ds.com',10,'mailstore1.secureserver.net'])
serverlist.append(['bc.com',10,'grid1i.seg.att.com'])
serverlist.append(['bc.com',20,'grid2i.seg.att.com'])
serverlist.append(['gha.com',20,'kempinski.com.s200a1.psmtp.com'])
serverlist.append(['gha.com',20,'kempinski.com.s200a2.psmtp.com'])
serverlist.append(['gha.com',50,'kempinski.com.s200b1.psmtp.com'])
serverlist.append(['gha.com',50,'kempinski.com.s200b2.psmtp.com'])
serverlist.append(['acme.in',0,'acme-in.mail.protection.outlook.com'])
serverlist.append(['icicisecurities.com',5,'hydisec2.icicibank.com'])
serverlist.append(['icicisecurities.com',5,'mlxisec1.icicibank.com'])
serverlist.append(['icicisecurities.com',5,'mlxisec2.icicibank.com'])
serverlist.append(['icicisecurities.com',5,'hydisec1.icicibank.com'])
serverlist.append(['live.in',5,'mx1.hotmail.com'])
serverlist.append(['live.in',5,'mx2.hotmail.com'])
serverlist.append(['live.in',5,'mx3.hotmail.com'])
serverlist.append(['live.in',5,'mx4.hotmail.com'])
serverlist.append(['licindia.com',30,'mail2.licindia.com'])
serverlist.append(['licindia.com',40,'mail3.licindia.com'])
serverlist.append(['licindia.com',50,'mail4.licindia.com'])
serverlist.append(['licindia.com',20,'mail.licindia.com'])
serverlist.append(['licindia.com',10,'mail1.licindia.com'])
serverlist.append(['nic.co.in',20,'nicmail3.nic.co.in'])
serverlist.append(['nic.co.in',10,'nicmail1.nic.co.in'])
serverlist.append(['nvsoft.com',1,'aspmx.l.google.com'])
serverlist.append(['nvsoft.com',10,'aspmx2.googlemail.com'])
serverlist.append(['nvsoft.com',10,'aspmx3.googlemail.com'])
serverlist.append(['nvsoft.com',5,'alt1.aspmx.l.google.com'])
serverlist.append(['nvsoft.com',5,'alt2.aspmx.l.google.com'])
serverlist.append(['heterodrugs.com',20,'cluster5a.us.messagelabs.com'])
serverlist.append(['heterodrugs.com',10,'cluster5.us.messagelabs.com'])
serverlist.append(['tges.org',10,'aspmx4.googlemail.com'])
serverlist.append(['tges.org',5,'alt2.aspmx.l.google.com'])
serverlist.append(['tges.org',10,'aspmx3.googlemail.com'])
serverlist.append(['tges.org',10,'aspmx5.googlemail.com'])
serverlist.append(['tges.org',1,'aspmx.l.google.com'])
serverlist.append(['tges.org',5,'alt1.aspmx.l.google.com'])
serverlist.append(['tges.org',10,'aspmx2.googlemail.com'])



import telnetlib, time
for i in range(6,len(serverlist)):

	# print ("Starting Client...")
	host    = serverlist[i][2]
	timeout = 20

	# print ("Connecting...")
	try:
	    session = telnetlib.Telnet(host, 25, timeout)
	    session.open(host,25,timeout)
	except socket.timeout:
	    print ("socket timeout")
	else:
	    # print("Sending Commands...")
	    session.write("helo local.domain.name\r".encode('ascii') + b"\r")
	    # session.write("helo local.domain.name\r\n".encode('ascii') + b"\r")
	    # print("Reading...")
	    initiate= session.read_until(b"/r/n/r/n#>", timeout-18 )
	    session.write(('MAIL FROM:vaibhavmay89@gmail.com'+'\r\n').encode('ascii') + b"\r")
	    session.write(('MAIL FROM:vaibhavmay89@gmail.com'+'\r\n').encode('ascii') + b"\r")
	    frommail= session.read_until(b"/r/n/r/n#>", timeout-18 )
	    session.write(('RCPT TO:info@'+serverlist[i][0]+'\r\n').encode('ascii') + b"\r")
	    check= session.read_until(b"/r/n/r/n#>", timeout-18 )

	    print(str(i)+'--' + initiate+'--'+frommail +'--'+check)
	    print(type(initiate),len(initiate))
	    print(type(frommail),len(frommail))
	    print(type(check),len(check))
	    print(host,'info@'+serverlist[i][0])

	    # print(output)
	    session.close()
	    print(str(i)+'+-------------------')