#[]






full = []

full.append([['3 BHK, 700 Sq-ft Builder Floor Apartment For Sale'], ['', '26.0 Lac(s)', '', '', ''], [" Dec 27, '14 ", ' ', ' 15201264 ', '', '', '', '', ''], [], ['RO Water System', 'Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Carpet/Builtup Area ', 'Additional Rooms ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['1 BHK, 550 Sq-ft Flat For Sale'], ['', '75.0 Lac(s)(Negotiable)', '', '', ''], [" Dec 27, '14 ", ' ', ' 15464686 ', '', '', '', '', ''], [], ['RO Water System', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Power Back Up', 'Rain Water Harvesting', 'Visitor Parking'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Carpet/Builtup Area ', 'Plot Area ', 'Additional Rooms ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['2 BHK, 975 Sq-ft Flat For Sale'], ['', '28.27 Lac(s)', '', ''], [" Dec 27, '14 ", ' ', ' 15465190 ', '', '', '', '', ''], [], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium', 'Swimming Pool'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Possession By', 'Floor Number', 'Total Floors', 'Covered Area ', 'Facing ', 'Overlooking ', 'Transaction Type ', 'Type of Ownership '], ['6 - N/A']])
full.append([['3 BHK, 1100 Sq-ft Builder Floor Apartment For Sale'], ['', '1.30 Crore(s)', '', '', ''], [" Dec 26, '14 ", ' ', ' 14695697 ', '', '', '', '', ''], [], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Visitor Parking', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Power Back Up', 'Rain Water Harvesting'], ['Address', 'Bedrooms', 'Bathrooms', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Plot Area ', 'Additional Rooms ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['4 BHK, 1700 Sq-ft Builder Floor Apartment For Sale'], ['', '1.70 Crore(s)', '', ''], [" Dec 26, '14 ", ' ', ' 15190425 ', '', '', '', '', ''], [], ['Private Terrace/Garden', 'Piped Gas', 'Park', 'Security', 'Water Storage', 'Visitor Parking'], ['Address', 'Bedrooms', 'Bathrooms', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Carpet/Builtup Area ', 'Additional Rooms ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['3 BHK, 1600 Sq-ft Flat For Sale'], ['', '1.20 Crore(s)', '', ''], [" Dec 26, '14 ", ' ', ' 15387034 ', '', '', '', '', ''], [], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Lift', 'Power Back Up', 'Service/Goods Lift', 'Rain Water Harvesting', 'Visitor Parking'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Carpet/Builtup Area ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['3 BHK, 850 Sq-ft Builder Floor Apartment For Sale'], ['', '54.0 Lac(s)(Negotiable)', '', ''], [" Dec 26, '14 ", ' ', ' 14889608 ', '', '', '', '', ''], [], ['Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium'], ['Address', 'Bedrooms', 'Bathrooms', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['3 BHK, 1800 Sq-ft Flat For Sale'], ['', '1.57 Crore(s)', '', '', ''], [" Dec 26, '14 ", ' ', ' 15418997 ', '', '', '', '', ''], [], ['RO Water System', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Carpet/Builtup Area ', 'Additional Rooms ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['3 BHK, 80 Sq-yrd Builder Floor Apartment For Sale'], ['', '26.0 Lac(s)(Negotiable)', '', ''], [" Dec 26, '14 ", ' ', ' 15457608 ', '', '', '', '', ''], [], ['Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Security', 'Laundry Service', 'Water Storage', 'DTH Television Facility', 'Service/Goods Lift', 'Visitor Parking'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Carpet/Builtup Area ', 'Plot Area ', 'Additional Rooms ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['3 BHK, 1650 Sq-ft Flat For Sale'], ['', '1.20 Crore(s)(Negotiable)', '', ''], [" Dec 26, '14 ", ' ', ' 15463332 ', '', '', '', '', ''], [], ['Vaastu Compliant', 'Piped Gas', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Outdoor Tennis Courts', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Facing ', 'Overlooking ', 'Age of Construction ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])
full.append([['2 BHK, 1050 Sq-ft Flat For Sale'], ['', '38.0 Lac(s)', '', ''], [" Dec 26, '14 ", ' ', ' 15229902 ', '', '', '', '', ''], [], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Gymnasium', 'Swimming Pool'], ['Address', 'Bedrooms', 'Bathrooms', 'Balconies', 'Furnished', 'Possession Status', 'Possession By', 'Floor Number', 'Total Floors', 'Units on the Floor ', 'Covered Area ', 'Facing ', 'Overlooking ', 'Transaction Type ', 'Type of Ownership ', 'Units Available '], ['6 - N/A']])