full = [] 




full = [] 




full.append([1, 'http://magicbricks.com/propertyDetails/3-BHK-700-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=ZtgMMpzJap5zpSvf+uAgZw==', ['\n3 BHK, 700 Sq-ft Builder Floor Apartment For Sale\n'], ['\n26.0 Lac(s)\n'], ['3,714/Sq-ft)'], ['15 %\n'], [" Dec 28, '14 "], ['RO Water System', 'Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['uttam nagar, New Delhi, Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['2 '], ['700'], ['690'], ['Puja Room'], ['East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([2, 'http://magicbricks.com/propertyDetails/1-BHK-550-Sq-ft-Multistorey-Apartment-FOR-Sale-Mayur-Vihar-1-in-New-Delhi&id=VTZCE1DNw6hzpSvf+uAgZw==', ['\n1 BHK, 550 Sq-ft Flat For Sale\n'], ['\n75.0 Lac(s)\n(Negotiable)\n'], ['13,636/Sq-ft)'], ['7 %\n'], [" Dec 27, '14 "], ['RO Water System', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Power Back Up', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['delhi police apartment plot no-1 delhi, mayur vihar -1, New Delhi - East - 110091'], ['1'], ['1'], ['2'], ['Furnished'], ['Ready to Move'], ['2 '], ['3 '], ['2 '], ['550'], ['525'], ['3'], ['Store'], ['North - West '], ['Garden/Park '], ['Above 20 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([3, 'http://magicbricks.com/propertyDetails/2-BHK-975-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-21-in-New-Delhi&id=VEqyAHkcPk5zpSvf+uAgZw==', ['\n2 BHK, 975 Sq-ft Flat For Sale\n'], ['\n28.27 Lac(s)\n'], ['2,900/Sq-ft)'], [], [" Dec 27, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Possession By'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Facing '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership ']], [['Dwarka Sector 21, New Delhi - Dwarka'], ['2'], ['2'], ['4'], ['Furnished'], ['Under Construction'], ["Jul, '19"], ['5 '], ['15 '], ['975'], ['North - East '], ['Garden/Park , Pool , Main Road '], ['New Property'], ['Freehold']]])
full.append([4, 'http://magicbricks.com/propertyDetails/3-BHK-1100-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Pitampura-in-New-Delhi&id=J2v++DUUxoFzpSvf+uAgZw==', ['\n3 BHK, 1100 Sq-ft Builder Floor Apartment For Sale\n'], ['\n1.30 Crore(s)\n'], ['11,818/Sq-ft)'], ['12 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Visitor Parking', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['52,Ashiana Apartments,Pitampura,New Delhi., Pitampura, New Delhi - North - 110034'], ['3'], ['3'], ['Furnished'], ['Ready to Move'], ['1 '], ['3 '], ['2 '], ['1100'], ['1'], ['Servant Room'], ['South - East '], ['Garden/Park , Main Road '], ['Above 20 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([5, 'http://magicbricks.com/propertyDetails/4-BHK-1700-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Shiva-Enclave-in-New-Delhi&id=2ailNos4T0dzpSvf+uAgZw==', ['\n4 BHK, 1700 Sq-ft Builder Floor Apartment For Sale\n'], ['\n1.70 Crore(s)\n'], ['10,000/Sq-ft)'], [], [" Dec 26, '14 "], ['Private Terrace/Garden', 'Piped Gas', 'Park', 'Security', 'Water Storage', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Shiva Enclave,Paschim Vihar,New Delhi, Shiva Enclave, Paschim Vihar, New Delhi - West - 110063'], ['4'], ['3'], ['Unfurnished'], ['Ready to Move'], ['2 '], ['2 '], ['1 '], ['1700'], ['1450'], ['Servant Room'], ['Garden/Park '], ['New Construction'], ['Resale'], ['Co-operative Society'], ['1']]])
full.append([6, 'http://magicbricks.com/propertyDetails/3-BHK-1600-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-12-in-New-Delhi&id=Hxev9tGyoYtzpSvf+uAgZw==', ['\n3 BHK, 1600 Sq-ft Flat For Sale\n'], ['\n1.20 Crore(s)\n'], ['7,500/Sq-ft)'], [], [" Dec 26, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Lift', 'Power Back Up', 'Service/Goods Lift', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['sector-12 park view apartment dwarka new delhi, Dwarka Sector 12, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['10 '], ['3 '], ['1600'], ['1400'], ['North - East '], ['Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([7, 'http://magicbricks.com/propertyDetails/3-BHK-850-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=TenqPuddHPxzpSvf+uAgZw==', ['\n3 BHK, 850 Sq-ft Builder Floor Apartment For Sale\n'], ['\n54.0 Lac(s)\n(Negotiable)\n'], ['6,353/Sq-ft)'], [], [" Dec 26, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, New Delhi, Delhi-NCR., Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['4 '], ['850'], ['North - East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([8, 'http://magicbricks.com/propertyDetails/3-BHK-1800-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-22-in-New-Delhi&id=T0jDsFOFqMtzpSvf+uAgZw==', ['\n3 BHK, 1800 Sq-ft Flat For Sale\n'], ['\n1.57 Crore(s)\n'], ['8,722/Sq-ft)'], ['9 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Classic Apartments Sector-22 Dwarka, Dwarka Sector 22, New Delhi - Dwarka - 110078'], ['3'], ['3'], ['4'], ['Unfurnished'], ['Ready to Move'], ['6 '], ['10 '], ['4 '], ['1800'], ['1500'], ['Store'], ['East '], ['Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['4']]])
full.append([9, 'http://magicbricks.com/propertyDetails/3-BHK-80-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=tgbLaR83vfhzpSvf+uAgZw==', ['\n3 BHK, 80 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n26.0 Lac(s)\n(Negotiable)\n'], ['32,500/Sq-yrd)'], [], [" Dec 26, '14 "], ['Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Security', 'Laundry Service', 'Water Storage', 'DTH Television Facility', 'Service/Goods Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['uttam nagar, Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['2 '], ['80'], ['75'], ['150'], ['Puja Room'], ['East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([10, 'http://magicbricks.com/propertyDetails/3-BHK-1650-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-12-in-New-Delhi&id=NTFX2bCkohJzpSvf+uAgZw==', ['\n3 BHK, 1650 Sq-ft Flat For Sale\n'], ['\n1.20 Crore(s)\n(Negotiable)\n'], ['7,273/Sq-ft)'], [], [" Dec 26, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Outdoor Tennis Courts', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Sector-12, Dwarka, Dwarka Sector 12, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['10 '], ['10 '], ['3 '], ['1650'], ['North - East '], ['Garden/Park , Main Road '], ['New Construction'], ['Resale'], ['Freehold'], ['1']]])
full.append([11, 'http://magicbricks.com/propertyDetails/2-BHK-1050-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-21-in-New-Delhi&id=dSJhHn11qspzpSvf+uAgZw==', ['\n2 BHK, 1050 Sq-ft Flat For Sale\n'], ['\n38.0 Lac(s)\n'], ['3,619/Sq-ft)'], [], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Gymnasium', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Possession By'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['L Zone, Dwarka Sector 21, New Delhi - Dwarka - 110077'], ['2'], ['2'], ['2'], ['Semi-Furnished'], ['Under Construction'], ["Dec, '18"], ['7 '], ['15 '], ['7 '], ['1050'], ['North - East '], ['Garden/Park , Pool , Main Road '], ['New Property'], ['Freehold'], ['1']]])
full.append([12, 'http://magicbricks.com/propertyDetails/3-BHK-217-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Safdarjung-Enclave-in-New-Delhi&id=ptiXu5O3tG9zpSvf+uAgZw==', ['\n3 BHK, 217 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n2.25 Crore(s)\n'], ['1.03 Lac(s)/Sq-yrd)'], [], [" Dec 26, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Waste Disposal', 'Park', 'Jogging and Strolling Track', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Club House', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['B-5 Block, B 5 Block, New Delhi - South - 110029'], ['3'], ['3'], ['1'], ['Furnished'], ['Ready to Move'], ['2 '], ['3 '], ['1 '], ['217'], ['South - East '], ['10 to 15 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([13, 'http://magicbricks.com/propertyDetails/1-BHK-650-Sq-ft-Multistorey-Apartment-FOR-Sale-Vasant-Kunj-Sector-D-in-New-Delhi&id=UPndPZI8+V5zpSvf+uAgZw==', ['\n1 BHK, 650 Sq-ft Flat For Sale\n'], ['\n60.0 Lac(s)\n(Negotiable)\n'], ['9,231/Sq-ft)'], [], [" Dec 26, '14 "], ['Private Terrace/Garden', 'Piped Gas', 'Air Conditioned', 'Maintenance Staff', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Power Back Up', 'Service/Goods Lift', 'Club House', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Kaveri apartment, Sector-d, Pkt 6., Vasant Kunj Sector D, New Delhi - South - 110070'], ['1'], ['2'], ['Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['12 '], ['650'], ['East '], ['Pool , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['4']]])
full.append([14, 'http://magicbricks.com/propertyDetails/2-BHK-800-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Dwarka-Sector-23-in-New-Delhi&id=R1GvMa0rS9hzpSvf+uAgZw==', ['\n2 BHK, 800 Sq-ft Builder Floor Apartment For Sale\n'], ['\n40.0 Lac(s)\n(Negotiable)\n'], ['5,000/Sq-ft)'], [], [" Dec 26, '14 "], ['Reserved Parking', 'Security', 'Lift', 'Club House'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Dwarka, Sec-23, A-79, Block-a, Pochanpur Extension, New Delhi, Dwarka Sector 23, New Delhi - Dwarka - 110077'], ['2'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['800'], ['East '], ['Garden/Park '], ['New Construction'], ['New Property'], ['POA'], ['1']]])
full.append([15, 'http://magicbricks.com/propertyDetails/3-BHK-1200-Sq-ft-Multistorey-Apartment-FOR-Sale-West-Enclave-in-New-Delhi&id=LRWnAUi9gE9zpSvf+uAgZw==', ['\n3 BHK, 1200 Sq-ft Flat For Sale\n'], ['\n1.0 Crore(s)\n'], ['8,333/Sq-ft)'], [], [" Dec 26, '14 "], [], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Pragati Apartments West Enclave Pitampura Delhi, West Enclave, Pitampura, New Delhi - North'], ['3'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['4 '], ['4 '], ['1200'], ['Puja Room'], ['East '], ['Garden/Park , Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([16, 'http://magicbricks.com/propertyDetails/4-BHK-2250-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Dwarka-Sector-12-in-New-Delhi&id=wi0zmD/sx11zpSvf+uAgZw==', ['\n4 BHK, 2250 Sq-ft Builder Floor Apartment For Sale\n'], ['\n2.75 Crore(s)\n(Negotiable)\n'], ['12,222/Sq-ft)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['dwarka sector 12, Dwarka Sector 12, New Delhi - Dwarka - 110075'], ['4'], ['4'], ['3'], ['Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['1 '], ['2250'], ['2000'], ['2250'], ['Servant Room'], ['East '], ['Garden/Park '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([17, 'http://magicbricks.com/propertyDetails/2-BHK-900-Sq-ft-Multistorey-Apartment-FOR-Sale-Bharthal-in-New-Delhi&id=I3XZaAuVULhzpSvf+uAgZw==', ['\n2 BHK, 900 Sq-ft Flat For Sale\n'], ['\n36.90 Lac(s)\n'], ['4,100/Sq-ft)'], [], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Possession By'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['ANTRIKSH VICTORIAN COUNTY, DWARKA, NEW DELHI, Bharthal, Dwarka, New Delhi - Dwarka'], ['2'], ['2'], ['4'], ['Semi-Furnished'], ['Under Construction'], ["Jun, '18"], ['6 '], ['27 '], ['2 '], ['900'], ['100'], ['Puja Room'], ['East '], ['Garden/Park , Pool , Main Road '], ['New Property'], ['Freehold'], ['1']]])
full.append([18, 'http://magicbricks.com/propertyDetails/3-BHK-725-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=RngvoQjnPuNzpSvf+uAgZw==', ['\n3 BHK, 725 Sq-ft Builder Floor Apartment For Sale\n'], ['\n36.0 Lac(s)\n'], ['4,966/Sq-ft)'], ['14 %\n'], [" Dec 24, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Water Storage', 'Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, New Delhi, Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['725'], ['700'], ['Store'], ['North - East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['8']]])
full.append([19, 'http://magicbricks.com/propertyDetails/3-BHK-830-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=zSAYG+rQBVVzpSvf+uAgZw==', ['\n3 BHK, 830 Sq-ft Builder Floor Apartment For Sale\n'], ['\n30.0 Lac(s)\n'], ['3,614/Sq-ft)'], [], [" Dec 24, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Waste Disposal', 'Water Storage', 'Lift'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Age of Construction '], ['Transaction Type ']], [['Uttam Nagar, New Delhi - West'], ['3'], ['2'], ['1'], ['Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['830'], ['New Construction'], ['New Property']]])
full.append([20, 'http://magicbricks.com/propertyDetails/1-BHK-505-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=ixXuk8frqRhzpSvf+uAgZw==', ['\n1 BHK, 505 Sq-ft Builder Floor Apartment For Sale\n'], ['\n16.71 Lac(s)\n'], ['3,309/Sq-ft)'], [], [" Dec 24, '14 "], ['RO Water System', 'Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Water Storage', 'Conference Room', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['NEAR WEST METRO STATION, UTTAM NAGARNEW DELHI, Uttam Nagar, New Delhi - West - 110059'], ['1'], ['1'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['2 '], ['505'], ['490'], ['2020'], ['North '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([21, 'http://magicbricks.com/propertyDetails/2-BHK-600-Sq-ft-Builder-Floor-Apartment-FOR-Sale-New-Uttam-Nagar-in-New-Delhi&id=kLzvkpgpWSZzpSvf+uAgZw==', ['\n2 BHK, 600 Sq-ft Builder Floor Apartment For Sale\n'], ['\n22.50 Lac(s)\n'], ['3,750/Sq-ft)'], [], [" Dec 24, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Water Storage', 'DTH Television Facility', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['UTTAM NAGAR, vishwash park, New Delhi - West - 110059'], ['2'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['2 '], ['600'], ['555'], ['1500'], ['Puja Room'], ['West '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([22, 'http://magicbricks.com/propertyDetails/4-BHK-4500-Sq-ft-Multistorey-Apartment-FOR-Sale-Jor-Bagh-in-New-Delhi&id=zvLRdLJaoORzpSvf+uAgZw==', ['\n4 BHK, 4500 Sq-ft Flat For Sale\n'], ['\n50.0 Crore(s)\n(Negotiable)\n'], ['1.11 Lac(s)/Sq-ft)'], [], [" Dec 24, '14 "], ['RO Water System', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Power Back Up', 'Conference Room', 'Club House', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Also many more options between 3-7 BHK New Builder Floor Apartments or Independent Houses in Panchsheel Park, Anand Lok, Defence Colony, Hauzkhas Enclave, SDA, Shanti Niketan, Westend, Anand Niketan, Vasant Vihar, Golf Links, Sunder Nagar, Jorbagh, Chanakyapuri etc..., Jor Bagh, New Delhi - South - 110003'], ['4'], ['4'], ['4'], ['Semi-Furnished'], ['Ready to Move'], ['Ground '], ['4 '], ['4500'], ['1'], ['Puja Room, Study, Store, Servant Room'], ['East '], ['Main Road , Garden/Park '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['7']]])
full.append([23, 'http://magicbricks.com/propertyDetails/4-BHK-2200-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-19-in-New-Delhi&id=zjRl/iQjv3BzpSvf+uAgZw==', ['\n4 BHK, 2200 Sq-ft Flat For Sale\n'], ['\n2.50 Crore(s)\n(Negotiable)\n'], ['11,364/Sq-ft)'], [], [" Dec 24, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Dwarka sector - 19, Dwarka, Dwarka Sector 19, New Delhi - Dwarka - 110075'], ['4'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['5 '], ['8 '], ['3 '], ['2200'], ['2000'], ['Servant Room'], ['North - East '], ['Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([24, 'http://magicbricks.com/propertyDetails/1-BHK-539-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-3-in-New-Delhi&id=ldJ6EDuhbWRzpSvf+uAgZw==', ['\n1 BHK, 539 Sq-ft Flat For Sale\n'], ['\n10.51 Lac(s)\n'], ['1,950/Sq-ft)'], [], [" Dec 24, '14 "], ['Park', 'Jogging and Strolling Track', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Mahaniyam prathana salai,\nMudichur,Manimangalam Road,\nTambaram, West,\nChennai., tambaram west, New Delhi - Dwarka'], ['1'], ['1'], ['1'], ['Unfurnished'], ['Under Construction'], ['2 '], ['4 '], ['539'], ['Garden/Park , Main Road '], ['New Property'], ['Freehold'], ['136']]])
full.append([25, 'http://magicbricks.com/propertyDetails/2-BHK-80-Sq-yrd-Multistorey-Apartment-FOR-Sale-Janakpuri-in-New-Delhi&id=ogstzPtdA15zpSvf+uAgZw==', ['\n2 BHK, 80 Sq-yrd Flat For Sale\n'], ['\n60.0 Lac(s)\n(Negotiable)\n'], ['75,000/Sq-yrd)'], [], [" Dec 24, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Reserved Parking', 'Waste Disposal', 'Park', 'Jogging and Strolling Track', 'Outdoor Tennis Courts', 'Security', 'Water Storage', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Janakpuri, New Delhi - West - 110058'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['3 '], ['1 '], ['80'], ['North - East '], ['Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([26, 'http://magicbricks.com/propertyDetails/2-BHK-650-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=N93o7Tb9IZBzpSvf+uAgZw==', ['\n2 BHK, 650 Sq-ft Builder Floor Apartment For Sale\n'], ['\n23.75 Lac(s)\n'], ['3,654/Sq-ft)'], [], [" Dec 23, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Water Storage'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['uttam nagar, Uttam Nagar, New Delhi - West - 110059'], ['2'], ['1'], ['1'], ['Furnished'], ['Ready to Move'], ['1 '], ['3 '], ['2 '], ['650'], ['East '], ['New Construction'], ['New Property'], ['Freehold'], ['3']]])
full.append([27, 'http://magicbricks.com/propertyDetails/3-BHK-1950-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-7-in-New-Delhi&id=rSSQ/TVkv/VzpSvf+uAgZw==', ['\n3 BHK, 1950 Sq-ft Flat For Sale\n'], ['\n1.84 Crore(s)\n(Negotiable)\n'], ['9,436/Sq-ft)'], ['3 %\n'], [" Dec 23, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['BRAHMA CGHS DWARKA SECTOR 7, Dwarka Sector 7, New Delhi - Dwarka - 110075'], ['3'], ['3'], ['4'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['10 '], ['2 '], ['1950'], ['1750'], ['Servant Room'], ['East '], ['Garden/Park '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([28, 'http://magicbricks.com/propertyDetails/2-BHK-950-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Hauz-Khas-in-New-Delhi&id=zPW6R8vJbKlzpSvf+uAgZw==', ['\n2 BHK, 950 Sq-ft Builder Floor Apartment For Sale\n'], ['\n82.0 Lac(s)\n(Negotiable)\n'], ['8,632/Sq-ft)'], [], [" Dec 23, '14 "], ['Vaastu Compliant', 'Reserved Parking', 'Park', 'Security', 'Water Storage', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Hauz Khas Village, Hauz Khas, New Delhi - South - 110016'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['3 '], ['3 '], ['950'], ['900'], ['2000'], ['Servant Room'], ['North - East '], ['Garden/Park '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([29, 'http://magicbricks.com/propertyDetails/3-BHK-1650-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-12-in-New-Delhi&id=qSTsEweKCr1zpSvf+uAgZw==', ['\n3 BHK, 1650 Sq-ft Flat For Sale\n'], ['\n1.55 Crore(s)\n'], ['9,394/Sq-ft)'], ['4 %\n'], [" Dec 22, '14 "], ['RO Water System', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'DTH Television Facility', 'Service/Goods Lift', 'Visitor Parking', 'Cafeteria/Food Court', 'Park', 'Security', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['KANAK DURGA APPTS SECTOR 12, Dwarka Sector 12, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['3'], ['Furnished'], ['Ready to Move'], ['3 '], ['8 '], ['4 '], ['1650'], ['North - East '], ['Garden/Park , Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([30, 'http://magicbricks.com/propertyDetails/3-BHK-1350-Sq-ft-Multistorey-Apartment-FOR-Sale-Patel-Nagar-in-New-Delhi&id=/Dxu6HrZYERzpSvf+uAgZw==', ['\n3 BHK, 1350 Sq-ft Flat For Sale\n'], ['\n3.0 Crore(s)\n'], ['22,222/Sq-ft)'], [], [" Dec 22, '14 "], ['Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Water Storage', 'Lift', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Possession By'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership ']], [['patel nagar, Patel Nagar, New Delhi - West - 110008'], ['3'], ['3'], ['2'], ['Unfurnished'], ['Under Construction'], ["Dec, '15"], ['3 '], ['4 '], ['1350'], ['1350'], ['Store'], ['North - East '], ['Main Road '], ['New Property'], ['Freehold']]])
full.append([31, 'http://magicbricks.com/propertyDetails/3-BHK-135-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Maidan-Garhi-in-New-Delhi&id=9h6uy751+rdzpSvf+uAgZw==', ['\n3 BHK, 135 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n43.0 Lac(s)\n'], ['31,852/Sq-yrd)'], [], [" Dec 21, '14 "], ['RO Water System', 'Vaastu Compliant', 'Reserved Parking', 'Waste Disposal', 'Security', 'Water Storage', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['maidan garhi, Maidan Garhi, Chhattarpur, New Delhi - South - 110068'], ['3'], ['2'], ['2'], ['Furnished'], ['Ready to Move'], ['2 '], ['3 '], ['135'], ['115'], ['North '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold']]])
full.append([32, 'http://magicbricks.com/propertyDetails/3-BHK-1733-Sq-ft-Multistorey-Apartment-FOR-Sale-Aashirwaad-Chowk-in-New-Delhi&id=F34A+KSA0X5zpSvf+uAgZw==', ['\n3 BHK, 1733 Sq-ft Flat For Sale\n'], ['\n1.07 Crore(s)\n'], ['6,174/Sq-ft)'], [], [" Dec 21, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Dwarka Sector 4., Aashirwaad Chowk, Dwarka, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['5 '], ['3 '], ['1733'], ['1402'], ['1'], ['Store'], ['North - East '], ['Garden/Park , Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([33, 'http://magicbricks.com/propertyDetails/3-BHK-1940-Sq-ft-Multistorey-Apartment-FOR-Sale-Commonwealth-Games-Village-2010-in-New-Delhi&id=vC0rxBHXQltzpSvf+uAgZw==', ['\n3 BHK, 1940 Sq-ft Flat For Sale\n'], ['\n3.48 Crore(s)\n'], ['17,938/Sq-ft)'], ['15 %\n'], [" Dec 21, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['CWG, Commonwealth Games Village 2010, Patparganj, New Delhi - East - 110092'], ['3'], ['4'], ['4'], ['Furnished'], ['Ready to Move'], ['4 '], ['6 '], ['1940'], ['Servant Room'], ['East '], ['Pool , Garden/Park '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['15']]])
full.append([34, 'http://magicbricks.com/propertyDetails/5-BHK-2831-Sq-ft-Multistorey-Apartment-FOR-Sale-Commonwealth-Games-Village-2010-in-New-Delhi&id=Uka3yeZyBRJzpSvf+uAgZw==', ['\n5 BHK, 2831 Sq-ft Flat For Sale\n'], ['\n5.70 Crore(s)\n'], ['20,134/Sq-ft)'], ['4 %\n'], [" Dec 20, '14 "], ['Piped Gas', 'Air Conditioned', 'Reserved Parking', 'Park', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Visitor Parking', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Common Wealth Games Village, East Facing, Commonwealth Games Village 2010, Patparganj, New Delhi - East'], ['5'], ['6'], ['5'], ['Semi-Furnished'], ['Ready to Move'], ['6 '], ['9 '], ['1 '], ['2831'], ['Servant Room'], ['East '], ['Garden/Park '], ['New Construction'], ['New Property'], ['Freehold'], ['1']]])
full.append([35, 'http://magicbricks.com/propertyDetails/2-BHK-975-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-21-in-New-Delhi&id=uxz8UQc4uzFzpSvf+uAgZw==', ['\n2 BHK, 975 Sq-ft Flat For Sale\n'], ['\n31.25 Lac(s)\n'], ['3,205/Sq-ft)'], [], [" Dec 20, '14 "], ['Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Possession By'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['near Nirmal Dhaam, Dwarka Sector 21, New Delhi - Dwarka - 110076'], ['2'], ['2'], ['2'], ['Semi-Furnished'], ['Under Construction'], ["Dec, '18"], ['6 '], ['15 '], ['460 '], ['975'], ['North - East '], ['Garden/Park , Pool , Main Road '], ['New Property'], ['Freehold'], ['300']]])
full.append([36, 'http://magicbricks.com/propertyDetails/2-BHK-1000-Sq-ft-Multistorey-Apartment-FOR-Sale-Indraprastha-Extension-in-New-Delhi&id=M3HxLIcWQYdzpSvf+uAgZw==', ['\n2 BHK, 1000 Sq-ft Flat For Sale\n'], ['\n1.10 Crore(s)\n'], ['11,000/Sq-ft)'], ['7 %\n'], [" Dec 27, '14 "], ['Internet/Wi-Fi Connectivity', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'DTH Television Facility', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['I.p.extension, Indraprastha Extension, Patparganj, New Delhi - East - 110092'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['1000'], ['Store'], ['North '], ['Garden/Park , Main Road '], ['15 to 20 years'], ['Resale'], ['Freehold']]])
full.append([37, 'http://magicbricks.com/propertyDetails/3-BHK-2300-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-2-in-New-Delhi&id=Ys9cYe1WblJzpSvf+uAgZw==', ['\n3 BHK, 2300 Sq-ft Flat For Sale\n'], ['\n1.85 Crore(s)\n'], ['8,043/Sq-ft)'], ['13 %\n'], [" Dec 27, '14 "], ['Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'Service/Goods Lift', 'Conference Room', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['PRAGYA APARTMENT, SECTOR-2 , DWARKA , NEW DELHI, Dwarka Sector 2, New Delhi - Dwarka - 110075'], ['3'], ['4'], ['4'], ['Unfurnished'], ['Ready to Move'], ['5 '], ['10 '], ['4 '], ['2300'], ['1900'], ['100000'], ['Servant Room'], ['North - East '], ['Garden/Park '], ['Less than 5 years'], ['New Property'], ['Freehold'], ['1']]])
full.append([38, 'http://magicbricks.com/propertyDetails/4-BHK-2600-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-12-in-New-Delhi&id=ouWCW5ATwylzpSvf+uAgZw==', ['\n4 BHK, 2600 Sq-ft Flat For Sale\n'], ['\n3.50 Crore(s)\n'], ['13,462/Sq-ft)'], [], [" Dec 27, '14 "], ['RO Water System', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Park', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Conference Room', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['5TH FLOOR SHIVANI APARTMENTS, Dwarka Sector 12, New Delhi - Dwarka - 110077'], ['4'], ['4'], ['4'], ['Unfurnished'], ['Ready to Move'], ['5 '], ['10 '], ['4 '], ['2600'], ['2100'], ['Servant Room'], ['North - East '], ['Garden/Park , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([39, 'http://magicbricks.com/propertyDetails/1-BHK-500-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=Ey3D+9bxUnA=', ['\n1 BHK, 500 Sq-ft Builder Floor Apartment For Sale\n'], ['\n23.11 Lac(s)\n'], ['4,622/Sq-ft)'], ['6 %\n'], [" Dec 27, '14 "], ['Private Terrace/Garden', 'Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'Banquet Hall', 'DTH Television Facility', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Security', 'Lift', 'Power Back Up', 'Rain Water Harvesting', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, New-Delhi, Delhi-NCR., Uttam Nagar, New Delhi - West - 110059'], ['1'], ['1'], ['1'], ['Furnished'], ['Ready to Move'], ['2 '], ['3 '], ['500'], ['Store'], ['East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['12']]])
full.append([40, 'http://magicbricks.com/propertyDetails/2-BHK-510-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Mahavir-Enclave-in-New-Delhi&id=bKXYiPHVDb5zpSvf+uAgZw==', ['\n2 BHK, 510 Sq-ft Builder Floor Apartment For Sale\n'], ['\n29.0 Lac(s)\n'], ['5,686/Sq-ft)'], ['11 %\n'], [" Dec 27, '14 "], ['Maintenance Staff', 'Security', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['Mahavir enclave., Mahavir Enclave, New Delhi - Dwarka - 110045'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['510'], ['West '], ['New Construction'], ['New Property'], ['Freehold']]])
full.append([41, 'http://magicbricks.com/propertyDetails/3-BHK-150-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Safdarjung-Enclave-in-New-Delhi&id=LKAIbR51XjBzpSvf+uAgZw==', ['\n3 BHK, 150 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n2.50 Crore(s)\n(Negotiable)\n'], ['1.66 Lac(s)/Sq-yrd)'], [], [" Dec 28, '14 "], ['Vaastu Compliant', 'Reserved Parking', 'Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Age of Construction '], ['Transaction Type ']], [['Safdarjung Enclave, New Delhi., Safdarjung Enclave, New Delhi - South'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['150'], ['New Construction'], ['Resale']]])
full.append([42, 'http://magicbricks.com/propertyDetails/3-BHK-1800-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-18-in-New-Delhi&id=1dA/adM1IndzpSvf+uAgZw==', ['\n3 BHK, 1800 Sq-ft Flat For Sale\n'], ['\n1.85 Crore(s)\n'], ['10,278/Sq-ft)'], ['12 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'Service/Goods Lift', 'Conference Room', 'Visitor Parking', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Sector-18, Dwarka, Dwarka Sector 18, New Delhi - Dwarka - 110075'], ['3'], ['3'], ['4'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['8 '], ['3 '], ['1800'], ['1700'], ['Puja Room, Servant Room'], ['North - East '], ['Garden/Park '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([43, 'http://magicbricks.com/propertyDetails/3-BHK-1300-Sq-ft-Multistorey-Apartment-FOR-Sale-Patparganj-in-New-Delhi&id=Fn9p+UZRpNNzpSvf+uAgZw==', ['\n3 BHK, 1300 Sq-ft Flat For Sale\n'], ['\n1.69 Crore(s)\n'], ['13,000/Sq-ft)'], ['5 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Reserved Parking', 'Park', 'Jogging and Strolling Track', 'Power Back Up', 'Conference Room', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['ipextension patparganj, Patparganj, New Delhi - East - 110092'], ['3'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['Ground '], ['4 '], ['1300'], ['1225'], ['4'], ['Store'], ['North - East '], ['Garden/Park , Pool '], ['15 to 20 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([44, 'http://magicbricks.com/propertyDetails/3-BHK-1500-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-2-in-New-Delhi&id=B5cfnMKbi11zpSvf+uAgZw==', ['\n3 BHK, 1500 Sq-ft Flat For Sale\n'], ['\n1.50 Crore(s)\n'], ['10,000/Sq-ft)'], ['8 %\n'], [" Dec 26, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Jogging and Strolling Track', 'Outdoor Tennis Courts', 'Security', 'Water Storage', 'Lift', 'Power Back Up', 'Service/Goods Lift', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Sector-2, Dwarka., Dwarka Sector 2, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['7 '], ['7 '], ['4 '], ['1500'], ['1350'], ['Study'], ['North - East '], ['Garden/Park '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([45, 'http://magicbricks.com/propertyDetails/2-BHK-520-Sq-ft-Multistorey-Apartment-FOR-Sale-Mahavir-Enclave-Part-1-in-New-Delhi&id=ex7QjqZq98xzpSvf+uAgZw==', ['\n2 BHK, 520 Sq-ft Flat For Sale\n'], ['\n27.0 Lac(s)\n'], ['5,192/Sq-ft)'], ['9 %\n'], [" Dec 26, '14 "], ['Vaastu Compliant', 'Water Storage', 'Power Back Up', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Mahavir Enclave, Delhi, Mahavir Enclave Part 1, New Delhi - Dwarka - 110045'], ['2'], ['1'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['1 '], ['520'], ['North - East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([46, 'http://magicbricks.com/propertyDetails/3-BHK-900-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Dwarka-Mor-in-New-Delhi&id=dLBUlECywEVzpSvf+uAgZw==', ['\n3 BHK, 900 Sq-ft Builder Floor Apartment For Sale\n'], ['\n45.0 Lac(s)\n'], ['5,000/Sq-ft)'], ['4 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Vaastu Compliant', 'Water Storage', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['B-1/63 Sewak Park Dwarka More,Near NSIT Collage,Sector-3 Dwarka, Dwarka Mor, New Delhi - Dwarka - 110059'], ['3'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['3 '], ['2 '], ['900'], ['850'], ['West '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([47, 'http://magicbricks.com/propertyDetails/3-BHK-1850-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-11-in-New-Delhi&id=rPouAukKCJNzpSvf+uAgZw==', ['\n3 BHK, 1850 Sq-ft Flat For Sale\n'], ['\n1.85 Crore(s)\n'], ['10,000/Sq-ft)'], ['3 %\n'], [" Dec 26, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'DTH Television Facility', 'Visitor Parking', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Sec-11, Plot-5B, Dwarka, Dwarka Sector 11, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['5 '], ['9 '], ['4 '], ['1850'], ['1650'], ['Study'], ['North - East '], ['Garden/Park , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([48, 'http://magicbricks.com/propertyDetails/2-BHK-560-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=yr8bON4PfFBzpSvf+uAgZw==', ['\n2 BHK, 560 Sq-ft Builder Floor Apartment For Sale\n'], ['\n22.0 Lac(s)\n'], ['3,929/Sq-ft)'], ['10 %\n'], [" Dec 26, '14 "], ['Intercom Facility', 'Reserved Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type ']], [['Uttam Nagar West., Uttam Nagar, New Delhi - West - 110059'], ['2'], ['1'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['2 '], ['560'], ['500'], ['West '], ['Main Road '], ['New Construction'], ['New Property']]])
full.append([49, 'http://magicbricks.com/propertyDetails/2-BHK-540-Sq-ft-Multistorey-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=dj7d2hPyAG0=', ['\n2 BHK, 540 Sq-ft Flat For Sale\n'], ['\n30.0 Lac(s)\n'], ['5,556/Sq-ft)'], ['14 %\n'], [" Dec 27, '14 "], ['Vaastu Compliant', 'Reserved Parking', 'Waste Disposal', 'Water Storage'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, New-Delhi, Delhi-NCR., Uttam Nagar, New Delhi - West - 110059'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['8 '], ['540'], ['1800'], ['North '], ['New Construction'], ['New Property'], ['Freehold'], ['1']]])
full.append([50, 'http://magicbricks.com/propertyDetails/3-BHK-1650-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-4-in-New-Delhi&id=m90iz2TZXfFzpSvf+uAgZw==', ['\n3 BHK, 1650 Sq-ft Flat For Sale\n'], ['\n1.35 Crore(s)\n'], ['8,182/Sq-ft)'], ['8 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['sec 4, dwarka, delhi, Dwarka Sector 4, New Delhi - Dwarka - 110075'], ['3'], ['2'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['8 '], ['2 '], ['1650'], ['1450'], ['1750'], ['East '], ['Garden/Park , Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([51, 'http://magicbricks.com/propertyDetails/3-BHK-120-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Dwarka-Sector-8-in-New-Delhi&id=rzsIba2c/TJzpSvf+uAgZw==', ['\n3 BHK, 120 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n1.10 Crore(s)\n'], ['91,667/Sq-yrd)'], [], [" Dec 26, '14 "], ['Piped Gas', 'Reserved Parking', 'Waste Disposal', 'Park', 'Jogging and Strolling Track', 'Security', 'Water Storage', 'Lift', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['A-block sec-8 dwarka near queens vally school, A-block, New Delhi - Dwarka - 110075'], ['3'], ['3'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['1 '], ['120'], ['Puja Room'], ['North - East '], ['Garden/Park , Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['4']]])
full.append([52, 'http://magicbricks.com/propertyDetails/4-BHK-2200-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-19-in-New-Delhi&id=pv7AWG5Ou3ZzpSvf+uAgZw==', ['\n4 BHK, 2200 Sq-ft Flat For Sale\n'], ['\n1.65 Crore(s)\n'], ['7,500/Sq-ft)'], [], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'Banquet Hall', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['Dwarka Sector 19, Dwarka Sector 19, New Delhi - Dwarka - 110075'], ['4'], ['3'], ['2'], ['Unfurnished'], ['Ready to Move'], ['6 '], ['10 '], ['2200'], ['1900'], ['Store'], ['North - East '], ['New Construction'], ['Resale'], ['Freehold']]])
full.append([53, 'http://magicbricks.com/propertyDetails/3-BHK-1460-Sq-ft-Multistorey-Apartment-FOR-Sale-Vasant-Kunj-Sector-D-in-New-Delhi&id=+tSoE/u1k5BzpSvf+uAgZw==', ['\n3 BHK, 1460 Sq-ft Flat For Sale\n'], ['\n1.90 Crore(s)\n'], ['13,014/Sq-ft)'], [], [" Dec 26, '14 "], ['Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Piped Gas', 'Maintenance Staff', 'Park', 'Jogging and Strolling Track', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Service/Goods Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['vasant kunj south delhi., Vasant Kunj Sector D, New Delhi - South - 110070'], ['3'], ['2'], ['3'], ['Unfurnished'], ['Ready to Move'], ['8 '], ['8 '], ['1460'], ['Store'], ['North - East '], ['Garden/Park , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold']]])
full.append([54, 'http://magicbricks.com/propertyDetails/3-BHK-715-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=UxVecn5ZXElzpSvf+uAgZw==', ['\n3 BHK, 715 Sq-ft Builder Floor Apartment For Sale\n'], ['\n34.25 Lac(s)\n(Negotiable)\n'], ['4,790/Sq-ft)'], ['10 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Water Storage', 'DTH Television Facility', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, New Delhi., Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['715'], ['North - East '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['3']]])
full.append([55, 'http://magicbricks.com/propertyDetails/3-BHK-120-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Mahavir-Enclave-Part-1-in-New-Delhi&id=HlLit0k06yRzpSvf+uAgZw==', ['\n3 BHK, 120 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n54.51 Lac(s)\n'], ['45,425/Sq-yrd)'], [], [" Dec 26, '14 "], [], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Age of Construction '], ['Transaction Type ']], [['Mahavir Enclave Part 1, New Delhi - Dwarka'], ['3'], ['2'], ['Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['120'], ['New Construction'], ['New Property']]])
full.append([56, 'http://magicbricks.com/propertyDetails/2-BHK-950-Sq-ft-Multistorey-Apartment-FOR-Sale-Patparganj-in-New-Delhi&id=4I0CyLKFt5VzpSvf+uAgZw==', ['\n2 BHK, 950 Sq-ft Flat For Sale\n'], ['\n1.20 Crore(s)\n(Negotiable)\n'], ['12,632/Sq-ft)'], ['2 %\n'], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Bar/Lounge', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Patparganj, New Delhi, Delhi-NCR., Patparganj, New Delhi - East - 110092'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['1 '], ['950'], ['Store'], ['North - East '], ['Garden/Park , Main Road '], ['15 to 20 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([57, 'http://magicbricks.com/propertyDetails/4-BHK-1480-Sq-ft-Multistorey-Apartment-FOR-Sale-Indraprastha-Extension-in-New-Delhi&id=xC7/fpdOZf1zpSvf+uAgZw==', ['\n4 BHK, 1480 Sq-ft Flat For Sale\n'], ['\n2.10 Crore(s)\n'], ['14,189/Sq-ft)'], [], [" Dec 26, '14 "], ['RO Water System', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['i.p.extension1, Indraprastha Extension, Patparganj, New Delhi - East - 110092'], ['4'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['6 '], ['7 '], ['2 '], ['1480'], ['Servant Room'], ['North - East '], ['Garden/Park , Main Road '], ['15 to 20 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([58, 'http://magicbricks.com/propertyDetails/2-BHK-950-Sq-ft-Multistorey-Apartment-FOR-Sale-Patparganj-in-New-Delhi&id=B04Xaou/sIhzpSvf+uAgZw==', ['\n2 BHK, 950 Sq-ft Flat For Sale\n'], ['\n1.10 Crore(s)\n'], ['11,579/Sq-ft)'], ['7 %\n'], [" Dec 26, '14 "], ['Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Power Back Up', 'Service/Goods Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Patparganj Ip Extention East Delhi, Patparganj ip Extn, New Delhi - East - 110092'], ['2'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['1 '], ['950'], ['Store'], ['East '], ['Garden/Park , Main Road '], ['10 to 15 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([59, 'http://magicbricks.com/propertyDetails/4-BHK-2400-Sq-ft-Multistorey-Apartment-FOR-Sale-Rohini-Sector-13-in-New-Delhi&id=P5fs23B3h0hzpSvf+uAgZw==', ['\n4 BHK, 2400 Sq-ft Flat For Sale\n'], ['\n2.70 Crore(s)\n'], ['11,250/Sq-ft)'], ['8 %\n'], [" Dec 26, '14 "], ['Private Terrace/Garden', 'Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Power Back Up', 'Club House', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['Sector -13, Rohini., Rohini Sector 13, New Delhi - Rohini - 110085'], ['4'], ['3'], ['Unfurnished'], ['Ready to Move'], ['3 '], ['4 '], ['2 '], ['2400'], ['1950'], ['Study, Store'], ['South -West '], ['Garden/Park , Main Road '], ['15 to 20 years'], ['Resale'], ['Freehold']]])
full.append([60, 'http://magicbricks.com/propertyDetails/2-BHK-900-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Shastri-Park-in-New-Delhi&id=lMk8TN7+MF1zpSvf+uAgZw==', ['\n2 BHK, 900 Sq-ft Builder Floor Apartment For Sale\n'], ['\n26.50 Lac(s)\n(Negotiable)\n'], ['2,944/Sq-ft)'], [], [" Dec 26, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Reserved Parking', 'Waste Disposal', 'Park', 'Water Storage', 'Power Back Up', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Shastri Park, New Delhi, Delhi-NCR., Shastri Park, Shahdara, New Delhi - North - 110094'], ['2'], ['2'], ['Furnished'], ['Ready to Move'], ['2 '], ['3 '], ['900'], ['1800'], ['North - East '], ['Garden/Park , Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['3']]])
full.append([61, 'http://magicbricks.com/propertyDetails/3-BHK-1400-Sq-ft-Multistorey-Apartment-FOR-Sale-Sarita-Vihar-Pocket-A-in-New-Delhi&id=yaUNIsUGn49zpSvf+uAgZw==', ['\n3 BHK, 1400 Sq-ft Flat For Sale\n'], ['\n1.60 Crore(s)\n'], ['11,429/Sq-ft)'], [], [" Dec 26, '14 "], ['Vaastu Compliant', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Water Storage', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['srita vihar, Sarita Vihar Pocket A, New Delhi - South - 110024'], ['3'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['3 '], ['1400'], ['1350'], ['North - East '], ['10 to 15 years'], ['Resale'], ['Freehold']]])
full.append([62, 'http://magicbricks.com/propertyDetails/2-BHK-1150-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-6-in-New-Delhi&id=/BsRe3IizkJzpSvf+uAgZw==', ['\n2 BHK, 1150 Sq-ft Flat For Sale\n'], ['\n1.07 Crore(s)\n'], ['9,304/Sq-ft)'], ['1 %\n'], [" Dec 26, '14 "], ['Internet/Wi-Fi Connectivity', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Park', 'Security', 'Banquet Hall', 'Water Storage', 'Lift', 'Power Back Up', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Dwarka Sector-6, New Delhi, Delhi-NCR., Dwarka Sector 6, New Delhi - Dwarka - 110077'], ['2'], ['2'], ['Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['1150'], ['950'], ['Servant Room'], ['Garden/Park '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([63, 'http://magicbricks.com/propertyDetails/2-BHK-675-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Hari-Nagar-in-New-Delhi&id=kYROIgf7xfdzpSvf+uAgZw==', ['\n2 BHK, 675 Sq-ft Builder Floor Apartment For Sale\n'], ['\n55.0 Lac(s)\n'], ['8,148/Sq-ft)'], ['5 %\n'], [" Dec 28, '14 "], ['Park', 'Security'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['C Block Hari Nagar, Hari Nagar, New Delhi - West - 110064'], ['2'], ['2'], ['2'], ['Unfurnished'], ['Ready to Move'], ['3 '], ['3 '], ['675'], ['675'], ['North '], ['Garden/Park , Main Road '], ['New Construction'], ['Resale'], ['Freehold']]])
full.append([64, 'http://magicbricks.com/propertyDetails/3-BHK-100-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Paschim-Vihar-in-New-Delhi&id=jV+KfTW1SypzpSvf+uAgZw==', ['\n3 BHK, 100 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n1.0 Crore(s)\n'], ['1.0 Lac(s)/Sq-yrd)'], [], [" Dec 26, '14 "], ['Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Water Storage', 'Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Facing '], ['Transaction Type ']], [['Paschim Vihar, New Delhi, Delhi-NCR., Paschim Vihar, New Delhi - West - 110087'], ['3'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['3 '], ['100'], ['North '], ['New Property']]])
full.append([65, 'http://magicbricks.com/propertyDetails/1-BHK-550-Sq-ft-Multistorey-Apartment-FOR-Sale-Vasant-Kunj-in-New-Delhi&id=mKJmRVsn2+ZzpSvf+uAgZw==', ['\n1 BHK, 550 Sq-ft Flat For Sale\n'], ['\n61.0 Lac(s)\n'], ['11,091/Sq-ft)'], [], [" Dec 26, '14 "], ['Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Service/Goods Lift', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['D-6, Vasant Kunj, New-Delhi, Delhi NCR., Vasant Kunj, New Delhi - South'], ['1'], ['2'], ['1'], ['Furnished'], ['Ready to Move'], ['4 '], ['5 '], ['550'], ['3'], ['Garden/Park '], ['New Construction'], ['Resale'], ['Freehold'], ['1']]])
full.append([66, 'http://magicbricks.com/propertyDetails/3-BHK-1600-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Vasant-Kunj-in-New-Delhi&id=dpxnjakmv2NzpSvf+uAgZw==', ['\n3 BHK, 1600 Sq-ft Builder Floor Apartment For Sale\n'], ['\n3.15 Crore(s)\n'], ['19,688/Sq-ft)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Reserved Parking', 'Waste Disposal', 'Park', 'Water Storage', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Vasant Kunj, New Delhi, Delhi-NCR., Vasant Kunj, New Delhi - South - 110070'], ['3'], ['2'], ['Furnished'], ['Ready to Move'], ['Ground '], ['3 '], ['1600'], ['Garden/Park '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['0']]])
full.append([67, 'http://magicbricks.com/propertyDetails/3-BHK-675-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=SdA0KmhCp6hzpSvf+uAgZw==', ['\n3 BHK, 675 Sq-ft Builder Floor Apartment For Sale\n'], ['\n36.0 Lac(s)\n(Negotiable)\n'], ['5,333/Sq-ft)'], [], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Security', 'Water Storage', 'Lift', 'DTH Television Facility', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Facing '], ['Overlooking '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, New-Delhi, Delhi-NCR., Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['675'], ['2250'], ['North '], ['Main Road '], ['New Property'], ['Freehold'], ['8']]])
full.append([68, 'http://magicbricks.com/propertyDetails/3-BHK-1400-Sq-ft-Multistorey-Apartment-FOR-Sale-Indraprastha-Extension-in-New-Delhi&id=FawTWn5oAypzpSvf+uAgZw==', ['\n3 BHK, 1400 Sq-ft Flat For Sale\n'], ['\n1.55 Crore(s)\n'], ['11,071/Sq-ft)'], ['7 %\n'], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Piped Gas', 'Maintenance Staff', 'Reserved Parking', 'Park', 'Security', 'Water Storage', 'Lift', 'DTH Television Facility', 'Power Back Up', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Plot Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Indraprastha Extension, New Delhi., Indraprastha Extension, Patparganj, New Delhi - East - 110092'], ['3'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['6 '], ['7 '], ['1400'], ['3'], ['East '], ['Garden/Park '], ['Above 20 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([69, 'http://magicbricks.com/propertyDetails/3-BHK-70-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Raja-Puri-in-New-Delhi&id=MgIbBDDzjCBzpSvf+uAgZw==', ['\n3 BHK, 70 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n24.0 Lac(s)\n'], ['34,286/Sq-yrd)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Water Storage', 'Visitor Parking', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Galino. 19 Rajapuri uttam nagar delhi, Raja Puri, Matiala, New Delhi - West - 110059'], ['3'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['2 '], ['70'], ['105'], ['Store'], ['North - West '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['4']]])
full.append([70, 'http://magicbricks.com/propertyDetails/3-BHK-1700-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-6-in-New-Delhi&id=P8IWIkz0V9xzpSvf+uAgZw==', ['\n3 BHK, 1700 Sq-ft Flat For Sale\n'], ['\n1.46 Crore(s)\n'], ['8,588/Sq-ft)'], ['9 %\n'], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['true frainds apartment secter 6 dwarka new delhi, Dwarka Sector 6, New Delhi - Dwarka - 110075'], ['3'], ['4'], ['4'], ['Furnished'], ['Ready to Move'], ['4 '], ['7 '], ['1 '], ['1700'], ['1400'], ['Store'], ['North - East '], ['Garden/Park '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([71, 'http://magicbricks.com/propertyDetails/3-BHK-1150-Sq-ft-Multistorey-Apartment-FOR-Sale-Mayur-Vihar-1-in-New-Delhi&id=wl4+cJdO+2VzpSvf+uAgZw==', ['\n3 BHK, 1150 Sq-ft Flat For Sale\n'], ['\n2.70 Crore(s)\n'], ['23,478/Sq-ft)'], [], [" Dec 25, '14 "], ['RO Water System', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Power Back Up', 'Service/Goods Lift', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['mayur vihar phase1, mayur vihar phase1, New Delhi - East - 110091'], ['3'], ['3'], ['3'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['7 '], ['2 '], ['1150'], ['Store'], ['East '], ['Garden/Park , Main Road '], ['10 to 15 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([72, 'http://magicbricks.com/propertyDetails/3-BHK-1860-Sq-ft-Multistorey-Apartment-FOR-Sale&id=fEoxFOZsrgBzpSvf+uAgZw==', ['\n3 BHK, 1860 Sq-ft Flat For Sale\n'], ['\n1.71 Crore(s)\n'], ['9,194/Sq-ft)'], [], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['PLOT NO 12 SECTOR 22 UDYOG VIHAR APARTMENT, SECTOR 22 DWARKA UDYOG VIHAR, New Delhi - 110075'], ['3'], ['3'], ['4'], ['Semi-Furnished'], ['Ready to Move'], ['5 '], ['10 '], ['2 '], ['1860'], ['North - East '], ['Garden/Park , Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['1']]])
full.append([73, 'http://magicbricks.com/propertyDetails/3-BHK-760-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=+SKZcFQgUZJzpSvf+uAgZw==', ['\n3 BHK, 760 Sq-ft Builder Floor Apartment For Sale\n'], ['\n30.21 Lac(s)\n'], ['3,975/Sq-ft)'], ['9 %\n'], [" Dec 25, '14 "], ['RO Water System', 'Private Terrace/Garden', 'Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Waste Disposal', 'Security', 'Water Storage', 'Lift', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Uttam Nagar, Uttam Nagar, New Delhi - West - 110059'], ['3'], ['2'], ['1'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['4 '], ['760'], ['750'], ['3000'], ['Puja Room'], ['North '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['1']]])
full.append([74, 'http://magicbricks.com/propertyDetails/3-BHK-1750-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-6-in-New-Delhi&id=nRzrt2BiTptzpSvf+uAgZw==', ['\n3 BHK, 1750 Sq-ft Flat For Sale\n'], ['\n1.53 Crore(s)\n'], ['8,743/Sq-ft)'], ['7 %\n'], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Banquet Hall', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Outdoor Tennis Courts', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting', 'Gymnasium'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Sector-6, Dwarka, Dwarka Sector 6, New Delhi - Dwarka - 110075'], ['3'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['5 '], ['10 '], ['4 '], ['1750'], ['1500'], ['Store'], ['North - East '], ['Garden/Park '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([75, 'http://magicbricks.com/propertyDetails/3-BHK-1700-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-in-New-Delhi&id=ZUl1LdRCRjdzpSvf+uAgZw==', ['\n3 BHK, 1700 Sq-ft Flat For Sale\n'], ['\n1.55 Crore(s)\n'], ['9,118/Sq-ft)'], ['6 %\n'], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Power Back Up', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Carpet/Builtup Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['Sector-6, Dwarka, New Delhi - Dwarka - 110075'], ['3'], ['3'], ['4'], ['Semi-Furnished'], ['Ready to Move'], ['4 '], ['8 '], ['1700'], ['1500'], ['Store'], ['East '], ['Garden/Park , Main Road '], ['5 to 10 years'], ['Resale'], ['Freehold']]])
full.append([76, 'http://magicbricks.com/propertyDetails/5-BHK-3755-Sq-ft-Multistorey-Apartment-FOR-Sale-Commonwealth-Games-Village-2010-in-New-Delhi&id=tssSsu//mjNzpSvf+uAgZw==', ['\n5 BHK, 3755 Sq-ft Flat For Sale\n'], ['\n7.85 Crore(s)\n'], ['20,905/Sq-ft)'], ['\n'], [" Dec 25, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Private Terrace/Garden', 'Vaastu Compliant', 'Piped Gas', 'Air Conditioned', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Water Storage', 'DTH Television Facility', 'Conference Room', 'Service/Goods Lift', 'Visitor Parking', 'Cafeteria/Food Court', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Club House', 'Rain Water Harvesting', 'Gymnasium', 'Swimming Pool'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Commonwealth Games village 2010, New Delhi, Commonwealth Games Village 2010, Patparganj, New Delhi - East - 110090'], ['5'], ['6'], ['5'], ['Semi-Furnished'], ['Ready to Move'], ['4 '], ['8 '], ['4 '], ['3755'], ['32'], ['Store, Servant Room'], ['East '], ['Garden/Park , Pool , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([77, 'http://magicbricks.com/propertyDetails/2-BHK-700-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Laxmi-Nagar-in-New-Delhi&id=wUzY+0Of8GBzpSvf+uAgZw==', ['\n2 BHK, 700 Sq-ft Builder Floor Apartment For Sale\n'], ['\n35.0 Lac(s)\n'], ['5,000/Sq-ft)'], [], [" Dec 25, '14 "], ['Reserved Parking', 'Waste Disposal', 'Water Storage'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Covered Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['Laxmi nagr, Laxmi Nagar, Laxmi Nagar, New Delhi - East - 110092'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['1 '], ['4 '], ['700'], ['South - East '], ['Less than 5 years'], ['Resale'], ['Freehold']]])
full.append([78, 'http://magicbricks.com/propertyDetails/2-BHK-50-Sq-yrd-Builder-Floor-Apartment-FOR-Sale-Govindpuri-Main-in-New-Delhi&id=jKfdFoSO53ZzpSvf+uAgZw==', ['\n2 BHK, 50 Sq-yrd Builder Floor Apartment For Sale\n'], ['\n26.50 Lac(s)\n'], ['53,000/Sq-yrd)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Water Storage', 'DTH Television Facility'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership ']], [['GOVINDPURI, Govindpuri Main, New Delhi - South - 110019'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['4 '], ['1 '], ['50'], ['New Construction'], ['New Property'], ['Freehold']]])
full.append([79, 'http://magicbricks.com/propertyDetails/4-BHK-2000-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-19-in-New-Delhi&id=RWP2RtFqqw9zpSvf+uAgZw==', ['\n4 BHK, 2000 Sq-ft Flat For Sale\n'], ['\n1.85 Crore(s)\n(Negotiable)\n'], ['9,250/Sq-ft)'], ['\n'], [" Dec 27, '14 "], ['RO Water System', 'Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Waste Disposal', 'Jogging and Strolling Track', 'Water Storage', 'DTH Television Facility', 'Service/Goods Lift', 'Visitor Parking', 'Reserved Parking', 'Park', 'Security', 'Laundry Service', 'Lift', 'Power Back Up', 'Rain Water Harvesting'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Dwarka Sector-19, New-Delhi, Delhi-NCR., Dwarka Sector 19, New Delhi - Dwarka'], ['4'], ['3'], ['Furnished'], ['Ready to Move'], ['4 '], ['10 '], ['4 '], ['2000'], ['North - West '], ['Garden/Park , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['1']]])
full.append([80, 'http://magicbricks.com/propertyDetails/2-BHK-700-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=jp0NZNYc+yFzpSvf+uAgZw==', ['\n2 BHK, 700 Sq-ft Builder Floor Apartment For Sale\n'], ['\n25.25 Lac(s)\n'], ['3,607/Sq-ft)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Plot Area '], ['Facing '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['subhash park uttam nagar n. delhi-59, Uttam Nagar, New Delhi - West - 110059'], ['2'], ['2'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['2 '], ['2 '], ['201 '], ['700'], ['1000'], ['East '], ['5 to 10 years'], ['Resale'], ['Freehold'], ['201']]])
full.append([81, 'http://magicbricks.com/propertyDetails/3-BHK-762-Sq-ft-Builder-Floor-Apartment-FOR-Sale-Uttam-Nagar-in-New-Delhi&id=An48fla+q39zpSvf+uAgZw==', ['\n3 BHK, 762 Sq-ft Builder Floor Apartment For Sale\n'], ['\n26.0 Lac(s)\n'], ['3,412/Sq-ft)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Intercom Facility', 'Reserved Parking', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Plot Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Raja puri uttam nagar, Raja puri uttam nagar, New Delhi - West - 110059'], ['3'], ['2'], ['1'], ['Unfurnished'], ['Ready to Move'], ['2 '], ['4 '], ['2 '], ['762'], ['758'], ['1239'], ['Puja Room'], ['North '], ['Main Road '], ['New Construction'], ['New Property'], ['Freehold'], ['2']]])
full.append([82, 'http://magicbricks.com/propertyDetails/4-BHK-1850-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-9-in-New-Delhi&id=PwF/nroE/V5zpSvf+uAgZw==', [], [], [], [], [], [], [], []])
full.append([83, 'http://magicbricks.com/propertyDetails/3-BHK-1250-Sq-ft-Multistorey-Apartment-FOR-Sale-Supreme-Enclave-in-New-Delhi&id=lnLMDGXvpdJzpSvf+uAgZw==', ['\n3 BHK, 1250 Sq-ft Flat For Sale\n'], ['\n1.90 Crore(s)\n'], ['15,200/Sq-ft)'], [], [" Dec 25, '14 "], ['Internet/Wi-Fi Connectivity', 'Vaastu Compliant', 'Piped Gas', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'Power Back Up', 'Service/Goods Lift', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Balconies'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Carpet/Builtup Area '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['301 Anand lok Apartment Mayur vihar Phase-1, Supreme Enclave, Mayur Vihar, New Delhi - North - 110091'], ['3'], ['3'], ['2'], ['Semi-Furnished'], ['Ready to Move'], ['3 '], ['7 '], ['3 '], ['1250'], ['1200'], ['North - East '], ['Garden/Park , Main Road '], ['15 to 20 years'], ['Resale'], ['Freehold'], ['2']]])
full.append([84, 'http://magicbricks.com/propertyDetails/5-BHK-2350-Sq-ft-Multistorey-Apartment-FOR-Sale-Dwarka-Sector-10-in-New-Delhi&id=BjS1ZIN5YOFzpSvf+uAgZw==', ['\n5 BHK, 2350 Sq-ft Flat For Sale\n'], ['\n2.68 Crore(s)\n'], ['11,404/Sq-ft)'], [], [" Dec 25, '14 "], ['Vaastu Compliant', 'Piped Gas', 'Intercom Facility', 'Maintenance Staff', 'Reserved Parking', 'Waste Disposal', 'Park', 'Security', 'Laundry Service', 'Water Storage', 'Lift', 'DTH Television Facility', 'Power Back Up', 'Rain Water Harvesting', 'Visitor Parking'], [['Address'], ['Bedrooms'], ['Bathrooms'], ['Furnished'], ['Possession Status'], ['Floor Number'], ['Total Floors'], ['Units on the Floor '], ['Covered Area '], ['Additional Rooms '], ['Facing '], ['Overlooking '], ['Age of Construction '], ['Transaction Type '], ['Type of Ownership '], ['Units Available ']], [['Dwarka Sector-10, New Delhi, Delhi-NCR., Dwarka Sector 10, New Delhi - Dwarka - 110075'], ['5'], ['5'], ['Furnished'], ['Ready to Move'], ['5 '], ['9 '], ['4 '], ['2350'], ['Servant Room'], ['North - East '], ['Garden/Park , Main Road '], ['Less than 5 years'], ['Resale'], ['Freehold'], ['1']]])


def filterst(st,j):
	
	######### ALL ###########
	remove = ['[',']','"',"'"]
	#print(type(st))
	for r in remove:
		st = st.replace(r,"")

	#print (st)
	if ((j == 1) or (j==3)): 
		remove = ["Rs.",","," "]
		for r in remove:
			st = st.replace(r,'')
	if (j == 2): 
		remove = ["OFF",","," "]
		for r in remove:
			st = st.replace(r,'')

	


	return st


def tester(st,j):
	remove = []
	
	split = None
	if j == 2 or j == 3 or j == 4 or j == 5: 
		st = str(st)
		remove.append('\n')
		remove.append("'")
		remove.append('%')
		remove.append(')')
		remove.append('(')
		remove.append(']')
		remove.append('[')
		remove.append('\\n')

		if j == 3: 
			split = " "
		if j == 4:
			split = "/"

		for i in remove: 
			while i in st: 
				st = st.replace(i,"")


		if split != None: 
			st = st.split(split)
	return(st)



for one in full:
	for j in range(0,len(one)):
		one[j] = tester(one[j],j)
	print ("fll.append("+str(one)+")\n")

specs = []
filter = 0 
for i in range (0,len(full)):
	for j in range(0,len(full[i][8])):
		if full[i][8][j] in specs:
			filter +=1
			continue
			
		else:

			specs.append(full[i][8][j])

for i in specs: 
	print (i)
print(str(len(specs)) +"    "+str(filter))


### NAME , Brand , PRICE , specs , 
###	for i in range(0,len(full[0])):
###	print(str(i)+":   "+str(full[0][i]))

new = []

for i in range (0,len(full)):
	new.append([full[i][0], full[i][1], full[i][2], full[i][3], full[i][4], full[i][5], full[i][6]])
	#for j in range(0,len(full[i][7])):
	for k in range(0,len(specs)) :
		try:
			#print("found one")
			index = full[i][8].index(specs[k])
			new[i].append(full[i][9][index])
			#print(str(i)+ ":   "+ full[i][8][index])
		except:
			new[i].append("N/A")


# building header
t = ''
for s in specs: 
	t += str(s)+ '"|"'

f = open("final.csv","w")
f.write('"name"|"cost"|"discount"|"originalPrice"|"ratings"|"noReviews"|"votes"|"'+ t+'"|ImageURL"')


for i in range(0,len(new)):
	f.write("\n")
	for j in range(0,len(new[i])):
		#print(j)
		f.write(str(new[i][j])+"|")
# for row in new: 
# 	f.write("\n"+ str(row))

f.close()
