#[]
full = []

full.append([['Asian Agencies Two Date Pocket A7 Diary Soft Bound'], [' Rs. 32 '], ['30% OFF'], [' Rs. 46 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AA 101', 'Diary', '150', 'Asian Agencies', 'Soft Bound', 'Black', 'A7', '105 mm', '70 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief 24 x 34 (A-5)', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Multicolour', 'Regular', '8 inch', '5.75 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Environmental Etiquettes A5 Diary Hard Bound'], [' Rs. 191 '], ['31% OFF'], [' Rs. 277 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '54-E', 'Diary', '365', 'Todays', 'Hard Bound', 'A5', 'Green', '9 inch', '6.25 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive Time Frame B5 Diary Hard Bound'], [' Rs. 179 '], ['31% OFF'], [' Rs. 260 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '82-TF', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Grey', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe ordinary', 'Diary', '328', 'Sapphire', 'Hard Bound', 'Blue', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Rhythmic Expression 2015 B7 Diary Hard Bound'], [' Rs. 110 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'RE-B7-B', 'Diary', '365', 'Nightingale', 'Hard Bound', 'B7', 'Multicolor', '5 inch', '7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([["Nightingale Canvas d'art 2015 A5 Diary Hard Bound"], [' Rs. 475 '], [], [], ['5'], ['0'], ['1'], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'CD-A5-C', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Multicolor', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 359 '], ['10% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 21 x 33 White,3', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Regular', 'Black', '9.875 inch', '7.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief natural,89', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Brown', 'Regular', '8.25 inch', '5.25 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 20 x 30 Natural', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Brown & Gold', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive B5 Diary Hard Bound'], [' Rs. 156 '], ['30% OFF'], [' Rs. 226 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '76', 'Diary', '365', 'Todays', 'Hard Bound', 'Brown', 'B5', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 248 '], ['9% OFF'], [' Rs. 275 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 60 Single Col', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Multicolour', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Day Planner 2015 A5 Diary Hard Bound'], [' Rs. 315 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'DP-A5-Blue', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Blue', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive A5 Diary Hard Bound'], [' Rs. 104 '], ['31% OFF'], [' Rs. 151 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '60', 'Diary', '365', 'Todays', 'Hard Bound', 'A5', 'Brown', '8.75 inch', '5.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 359 '], ['10% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 21 X 33 Natural Shade', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Regular', 'Gold', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Go Green Diary,50', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Black & Green', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Peace Diary', 'Diary', '368', 'Sapphire', 'Hard Bound', 'Regular', 'Blue', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], ['1'], ['0'], ['1'], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Multi Col Diary', 'Diary', '400', 'Sapphire', 'Hard Bound', 'Regular', 'Multicolour', '8.25 inch', '5.25 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Rhythmic Expression 2015 B7 Diary Hard Bound'], [' Rs. 110 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'RE-B7-D', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Multicolor', 'B7', '5 inch', '7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Business Organiser A5 Diary Hard Bound'], [' Rs. 408 '], ['31% OFF'], [' Rs. 592 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'Rab391', 'Diary', '365', 'Todays', 'Hard Bound', 'Black', 'A5', '7.75 inch', '5.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies Three Date Personal B7 Diary Hard Bound'], [' Rs. 77 '], ['29% OFF'], [' Rs. 108 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AA 102', 'Diary', '100', 'Asian Agencies', 'Hard Bound', 'B7', 'Green', '175 mm', '90 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Multi Col Diary', 'Diary', '400', 'Sapphire', 'Hard Bound', 'Regular', 'Brown', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 179 '], ['10% OFF'], [' Rs. 199 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief 2 Date A Page, 97', 'Diary', '176', 'Sapphire', 'Hard Bound', 'Black', 'Regular', '8.25 inch', '5.25 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 248 '], ['9% OFF'], [' Rs. 275 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 60 Single Col NOTE BOOK', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Regular', 'Multicolour', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive A5 Diary Hard Bound'], [' Rs. 128 '], ['31% OFF'], [' Rs. 186 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '62', 'Diary', '365', 'Todays', 'Hard Bound', 'Brown', 'A5', '8.75 inch', '5.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 179 '], ['10% OFF'], [' Rs. 199 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book White Planner,128', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Regular', 'Black', '8.5 inch', '5.5 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 206 '], ['10% OFF'], [' Rs. 229 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Nt Book 24x34 (A-5) Natural', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Pink', 'Regular', '8 inch', '5.75 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive A5 Diary Hard Bound'], [' Rs. 143 '], ['30% OFF'], [' Rs. 207 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '65', 'Diary', '365', 'Todays', 'Hard Bound', 'A5', 'Pink', '8.75 inch', '5.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 260 '], ['38% OFF'], [' Rs. 421 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE14', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'B7', 'Blue', '9.75 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive B5 Diary Hard Bound'], [' Rs. 146 '], ['31% OFF'], [' Rs. 212 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '75', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Multi', '9.75 inch', '7.25 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Library 2015 A4 Diary Hard Bound'], [' Rs. 985 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'L-A4-Black', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A4', 'Black', '8 inch', '12 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Ooops! Something went wrong.'], [], [], [], [], [], [], [], [], []])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 206 '], ['10% OFF'], [' Rs. 229 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Commercial 1 Date Diary 99', 'Diary', '328', 'Sapphire', 'Hard Bound', 'Blue', 'Regular', '7.75 inch', '4.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive B5 Diary Hard Bound'], [' Rs. 240 '], ['31% OFF'], [' Rs. 348 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '87', 'Diary', '365', 'Todays', 'Hard Bound', 'Brown', 'B5', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Super Executive B5 Diary Hard Bound'], [' Rs. 294 '], ['30% OFF'], [' Rs. 426 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '9', 'Diary', '365', 'Todays', 'Hard Bound', 'Brown', 'B5', '10.25 inch', '8.25 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 338 '], ['9% OFF'], [' Rs. 375 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 21 X 33 White', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Blue & Brown', 'Regular', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Business Organizer 2015 B7 Diary Hard Bound'], [' Rs. 545 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'O-B7-Maroon', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Maroon', 'B7', '5 inch', '7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 248 '], ['9% OFF'], [' Rs. 275 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Big', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Green', 'Regular', '25 cm', '18.5 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive B5 Diary Hard Bound'], [' Rs. 214 '], ['30% OFF'], [' Rs. 310 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '90', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Brown', '10.25 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 248 '], ['9% OFF'], [' Rs. 275 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Big 24 X 34 ( A5)', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Regular', 'Black', '8.375 inch', '6 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 315 '], ['36% OFF'], [' Rs. 499 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE18', 'Diary', '360', 'Gathbandhan', 'Hard Bound', 'Gold, Brown', 'B7', '9.75 inch', '1 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 359 '], ['10% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Innovation Diary,53', 'Diary', '368', 'Sapphire', 'Hard Bound', 'Red', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Library 2015 B5 Diary Hard Bound'], [' Rs. 650 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'L-B5-Black', 'Diary', '365', 'Nightingale', 'Hard Bound', 'B5', 'Black', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Business Organizer 2015 B7 Diary Hard Bound'], [' Rs. 545 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'O-B7-Black', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Black', 'B7', '5 inch', '7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 203 '], ['9% OFF'], [' Rs. 225 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book White Planner,127', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Regular', 'Black', '8.5 inch', '5.5 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Business Organizer 2015 B5 Diary Hard Bound'], [' Rs. 765 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'O-B5-Black', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Black', 'B5', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 240 '], ['32% OFF'], [' Rs. 357 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE24', 'Diary', '360', 'Gathbandhan', 'Hard Bound', 'Brown', 'B7', '7.5 inch', '1 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 60 Single Col Planner', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Black', 'Regular', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive B5 Diary Hard Bound'], [' Rs. 179 '], ['31% OFF'], [' Rs. 260 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '77', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Multi', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Ooops! Something went wrong.'], [], [], [], [], [], [], [], [], []])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 206 '], ['10% OFF'], [' Rs. 229 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief 60 Single Col Diary', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Regular', 'Multicolor', '21 cm', '15 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies One Date Nescafe B5 Diary Hard Bound'], [' Rs. 378 '], ['30% OFF'], [' Rs. 540 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AA 106', 'Diary', '150', 'Asian Agencies', 'Hard Bound', 'B5', 'Red', '250 mm', '190 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([["Nightingale Canvas d'art 2015 A5 Diary Hard Bound"], [' Rs. 475 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'CD-A5-B', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Multicolor', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Note Book Regular Notebook Soft Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book (A-5) Cremepaper', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Regular', 'Gold', '21 cm', '15 cm', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Business Organiser A5 Diary Hard Bound'], [' Rs. 195 '], ['31% OFF'], [' Rs. 283 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '25', 'Diary', '365', 'Todays', 'Hard Bound', 'Amber', 'A5', '8.5 inch', '6 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Library 2015 A5 Diary Hard Bound'], [' Rs. 495 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'L-A5-Black', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Black', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Innovation diary', 'Diary', '368', 'Sapphire', 'Hard Bound', 'Grey', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 280 '], ['22% OFF'], [' Rs. 360 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE8', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'B7', 'Green, White', '9.25 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Eco 2015 A5 Diary Hard Bound'], [' Rs. 325 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'E-A5-C', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Multicolor', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 179 '], ['10% OFF'], [' Rs. 199 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book White Planner', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Regular', 'White & Yellow', '8.5 inch', '5.5 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Big,66', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Black & Red', 'Regular', '8.375 inch', '6 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 338 '], ['9% OFF'], [' Rs. 375 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief 70 single Col,70', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Regular', 'Black', '8.25 inch', '5.25 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Business Organizer 2015 B5 Diary Hard Bound'], [' Rs. 765 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'O-B5-Blue', 'Diary', '365', 'Nightingale', 'Hard Bound', 'B5', 'Blue', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive Inspire Big B5 Diary Hard Bound'], [' Rs. 218 '], ['31% OFF'], [' Rs. 316 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '10-IB', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Grey', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Noble Emperor 2015 B5 Diary Hard Bound'], [' Rs. 1,070 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'NE-B5-Blue', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Blue', 'B5', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive Key To Success B5 Diary Hard Bound'], [' Rs. 179 '], ['31% OFF'], [' Rs. 260 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '82-KTS', 'Diary', '365', 'Todays', 'Hard Bound', 'Scarlet', 'B5', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies Two Date Nescafe B5 Diary Hard Bound'], [' Rs. 189 '], ['30% OFF'], [' Rs. 270 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AA 105', 'Diary', '110', 'Asian Agencies', 'Hard Bound', 'B5', 'Black', '250 mm', '190 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corporate 2015 A5 Diary Hard Bound'], [' Rs. 395 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'Co-A5-Burgandy', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Burgandy', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Go Green Diary', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Multicolour', 'Regular', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 350 '], ['29% OFF'], [' Rs. 499 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE15', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'Brown', 'B7', '9.75 inch', '1 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 203 '], ['9% OFF'], [' Rs. 225 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Multi Col Note Book', 'Notebook', '264', 'Sapphire', 'Soft Bound', 'Regular', 'Multicolour', '8.5 inch', '5.375 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 320 '], ['5% OFF'], [' Rs. 340 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE6', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'B7', 'Green, White', '8.5 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Soft Bound'], [' Rs. 206 '], ['10% OFF'], [' Rs. 229 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief 60 Single Col', 'Diary', '336', 'Sapphire', 'Soft Bound', 'Regular', 'Black', '21 cm', '15 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([["Nightingale Canvas d'art 2015 A5 Diary Hard Bound"], [' Rs. 475 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'CD-A5-D', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Multicolor', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Sunday Seprate', 'Diary', '400', 'Sapphire', 'Hard Bound', 'Regular', 'Orange', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corduroy 2015 B5 Diary Hard Bound'], [' Rs. 495 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'C-B5-Charcoal', 'Diary', '365', 'Nightingale', 'Hard Bound', 'B5', 'Black', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 206 '], ['10% OFF'], [' Rs. 229 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book (A-5) CremePaper', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Regular', 'Pink', '8 inch', '5.75 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies One Date Nescafe B5 Diary Hard Bound'], [' Rs. 353 '], ['30% OFF'], [' Rs. 504 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AA 108', 'Diary', '160', 'Asian Agencies', 'Hard Bound', 'Black', 'B5', '265 mm', '190 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Multi Colour Diary', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Regular', 'Black', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 249 '], ['30% OFF'], [' Rs. 356 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE7', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'Red', 'B7', '9 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies Two Date Personal B7 Diary Hard Bound'], [' Rs. 81 '], ['30% OFF'], [' Rs. 115 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AA 103', 'Diary', '140', 'Asian Agencies', 'Hard Bound', 'B7', 'Red', '175 mm', '90 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive Special Moments B5 Diary Hard Bound'], [' Rs. 179 '], ['31% OFF'], [' Rs. 260 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '82-SM', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Blue', '9.75 inch', '7.25 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies One Date Chief A5 Diary Hard Bound'], [' Rs. 343 '], ['30% OFF'], [' Rs. 490 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AA 104', 'Diary', '150', 'Asian Agencies', 'Hard Bound', 'A5', 'Red', '215 mm', '150 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 260 '], ['25% OFF'], [' Rs. 350 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE19', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'B7', 'Maroon', '9.75 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 359 '], ['10% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Peace On Earth,56', 'Diary', '368', 'Sapphire', 'Hard Bound', 'Regular', 'Black & Red', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 225 '], ['36% OFF'], [' Rs. 357 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE12', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'B7', 'Brown', '9 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corporate 2015 A5 Diary Hard Bound'], [' Rs. 395 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'Co-A5-Black', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Black', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 248 '], ['9% OFF'], [' Rs. 275 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Big 24 X 34 ( A5)', 'Notebook', '352', 'Sapphire', 'Soft Bound', 'Pink', 'Regular', '8.375 inch', '6 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 359 '], ['10% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 20 X 30 Natural Shade', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Regular', 'Gold', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Peace On Earth Diary', 'Diary', '368', 'Sapphire', 'Hard Bound', 'Black', 'Regular', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book Multi Col. 117', 'Notebook', '264', 'Sapphire', 'Soft Bound', 'Regular', 'Black', '8.5 inch', '5.5 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corduroy 2015 A5 Diary Hard Bound'], [' Rs. 395 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'C-A5-Charcoal', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Black', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 210 '], ['41% OFF'], [' Rs. 356 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE9', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'B7', 'Brown', '9.25 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Note Book Natural', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Beige', 'Regular', '9.5 inch', '7.125 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Wiro B5 Diary Soft Bound'], [' Rs. 284 '], ['31% OFF'], [' Rs. 412 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '2', 'Diary', '365', 'Todays', 'Soft Bound', 'Green', 'B5', '9.5 inch', '7.25 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 230 '], ['23% OFF'], [' Rs. 300 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE1', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'Grey, Brown', 'B7', '8.5 inch', '0.7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 203 '], ['9% OFF'], [' Rs. 225 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Chief Note Book', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Multicolour', 'Regular', '8.5 inch', '5.5 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 60 Double Col', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Regular', 'Black & Cream', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corporate 2015 B5 Diary Hard Bound'], [' Rs. 495 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'Co-B5-Blue', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Blue', 'B5', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 280 '], ['37% OFF'], [' Rs. 450 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE21', 'Diary', '360', 'Gathbandhan', 'Hard Bound', 'B7', 'Brown', '10 inch', '1 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 260 '], ['43% OFF'], [' Rs. 458 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE20', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'B7', 'Gold', '9.75 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 250 '], ['30% OFF'], [' Rs. 360 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE4', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'Brown, Blue, Grey', 'B7', '9 inch', '0.7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 210 '], ['41% OFF'], [' Rs. 356 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE2', 'Diary', '150', 'Gathbandhan', 'Hard Bound', 'B7', 'Grey, Orange', '9 inch', '0.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive Yes We Can B5 Diary Hard Bound'], [' Rs. 218 '], ['31% OFF'], [' Rs. 316 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', '10-YWC', 'Diary', '365', 'Todays', 'Hard Bound', 'B5', 'Brown', '10 inch', '7.5 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 260 '], ['25% OFF'], [' Rs. 350 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE10', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'B7', 'Maroon', '9 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 270 '], ['32% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE16', 'Diary', '320', 'Gathbandhan', 'Hard Bound', 'Blue, Grey', 'B7', '10 inch', '1 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 210 '], ['41% OFF'], [' Rs. 356 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE3', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'Brown', 'B7', '8 inch', '0.7 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Asian Agencies One Date Nescafe B5 Diary Hard Bound'], [' Rs. 333 '], ['31% OFF'], [' Rs. 480 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AA 107', 'Diary', '190', 'Asian Agencies', 'Hard Bound', 'B5', 'Red', '250 mm', '190 mm'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Todays Executive Go Green B5 Diary Hard Bound'], [' Rs. 179 '], ['31% OFF'], [' Rs. 260 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', '82-GG', 'Diary', '365', 'Todays', 'Hard Bound', 'Green', 'B5', '9.75 inch', '7.25 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 230 '], ['35% OFF'], [' Rs. 356 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AONE11', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'B7', 'Brown', '9.5 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 310 '], ['37% OFF'], [' Rs. 499 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE17', 'Diary', '360', 'Gathbandhan', 'Hard Bound', 'Gold, Brown', 'B7', '9.5 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Gathbandhan 2015 Exclusive B7 Diary Hard Bound'], [' Rs. 210 '], ['41% OFF'], [' Rs. 356 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AONE13', 'Diary', '310', 'Gathbandhan', 'Hard Bound', 'Brown', 'B7', '8.5 inch', '0.75 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Note Book Regular Notebook Soft Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Note Book Creme Paper Flexi', 'Notebook', '240', 'Sapphire', 'Soft Bound', 'Regular', 'Beige', '26.5 cm', '21 cm', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 293 '], ['9% OFF'], [' Rs. 325 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Engineering Diary', 'Diary', '368', 'Sapphire', 'Hard Bound', 'Regular', 'Blue', '26.5 cm', '21 cm', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Ooops! Something went wrong.'], [], [], [], [], [], [], [], [], []])
full.append([['Nightingale Corporate 2015 A5 Diary Hard Bound'], [' Rs. 395 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'Co-A5-Blue', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Blue', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Eco 2015 A5 Diary Hard Bound'], [' Rs. 325 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'E-A5-A', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Multicolor', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corporate 2015 A5 Diary Hard Bound'], [' Rs. 395 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'Co-A5-Grey', 'Diary', '365', 'Nightingale', 'Hard Bound', 'A5', 'Grey', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Natural,34', 'Diary', '336', 'Sapphire', 'Hard Bound', 'Regular', 'Brown', '9.375 inch', '6.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 269 '], ['10% OFF'], [' Rs. 299 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Note Book, Multi Col 107', 'Notebook', '264', 'Sapphire', 'Soft Bound', 'Brown', 'Regular', '9.5 inch', '7.125 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Multi Col Note Book', 'Notebook', '264', 'Sapphire', 'Soft Bound', 'Regular', 'Multicolour', '9.5 inch', '7.125 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Eco 2015 A5 Diary Hard Bound'], [' Rs. 325 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'E-A5-D', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Multicolor', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Notes Regular Notebook Soft Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Note Book,109', 'Notebook', '232', 'Sapphire', 'Soft Bound', 'Black', 'Regular', '9.5 inch', '7.125 inch', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Artcover 2015 A5 Diary Hard Bound'], [' Rs. 195 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'AC-A5-H', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Multicolor', 'A5', '6 inch', '8 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Artcover 2015 B5 Diary Hard Bound'], [' Rs. 265 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width'], ['Ruled', 'AC-B5-H', 'Diary', '365', 'Nightingale', 'Hard Bound', 'B5', 'Multicolor', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire 2015 Regular Diary Hard Bound'], [' Rs. 359 '], ['10% OFF'], [' Rs. 399 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 20 x 30 White', 'Diary', '352', 'Sapphire', 'Hard Bound', 'Regular', 'Grey', '9.875 inch', '7.875 inch', 'Diary'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Note Book Regular Notebook Soft Bound'], [' Rs. 224 '], ['10% OFF'], [' Rs. 249 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Size', 'Color', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe Note Book', 'Notebook', '232', 'Sapphire', 'Soft Bound', 'Regular', 'Green & Orange', '26.5 cm', '21 cm', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Sapphire Note Book Regular Notebook Soft Bound'], [' Rs. 248 '], ['9% OFF'], [' Rs. 275 '], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width', 'Sales Package'], ['Ruled', 'Nescafe 60 Single Col', 'Notebook', '336', 'Sapphire', 'Soft Bound', 'Beige', 'Regular', '26.5 cm', '21 cm', 'Notebook'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])
full.append([['Nightingale Corporate 2015 B5 Diary Hard Bound'], [' Rs. 495 '], [], [], [], [], [], ['Ruling', 'Model id', 'Type', 'No. of Pages', 'Brand Name', 'Binding', 'Color', 'Size', 'Length', 'Width'], ['Ruled', 'Co-B5-Grey', 'Diary', '365', 'Nightingale', 'Hard Bound', 'Grey', 'B5', '7 inch', '9 inch'], ['http://img1a.flixcart.com/img/thumb-default.jpg']])

def filterst(st,j):
	
	######### ALL ###########
	remove = ['[',']','"',"'"]
	#print(type(st))
	for r in remove:
		st = st.replace(r,"")

	#print (st)
	if ((j == 1) or (j==3)): 
		remove = ["Rs.",","," "]
		for r in remove:
			st = st.replace(r,'')
	if (j == 2): 
		remove = ["OFF",","," "]
		for r in remove:
			st = st.replace(r,'')

	


	return st


#[ 'name',  'cost',  "discount",  "originalPrice",  "ratings",  "noReviews",  "votes",  "speckey",  "specvalue",  'ImageURL' ]
specs = []
filter = 0 
for i in range (0,len(full)):
	for j in range(0,len(full[i][7])):
		if full[i][7][j] in specs:
			filter +=1
			continue
			
		else:

			specs.append(full[i][7][j])

for i in specs: 
	print (i)
print(str(len(specs)) +"    "+str(filter))


### NAME , Brand , PRICE , specs , 
###	for i in range(0,len(full[0])):
###	print(str(i)+":   "+str(full[0][i]))

new = []

for i in range (0,len(full)):
	new.append([full[i][0], full[i][1], full[i][2], full[i][3], full[i][4], full[i][5], full[i][6]])
	#for j in range(0,len(full[i][7])):
	for k in range(0,len(specs)) :
		try:
			#print("found one")
			index = full[i][7].index(specs[k])
			new[i].append(full[i][8][index])
			#print(str(i)+ ":   "+ full[i][8][index])
		except:
			new[i].append("N/A")


# building header
t = ''
for s in specs: 
	t += s+ '"|"'

f = open("final.csv","w")
f.write('"name"|"cost"|"discount"|"originalPrice"|"ratings"|"noReviews"|"votes"|"'+ t+'"|ImageURL"')


for i in range(0,len(new)):
	f.write("\n")
	for j in range(0,len(new[i])):
		#print(j)
		f.write(filterst(str(new[i][j]),j)+"|")
# for row in new: 
# 	f.write("\n"+ str(row))

f.close()




